# Generated by Django 4.2.7 on 2025-11-11 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messagerie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailInterneDestinataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lu', models.BooleanField(default=False)),
                ('important', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Destinataire d'e-mail",
                'verbose_name_plural': "Destinataires d'e-mails",
            },
        ),
        migrations.RemoveIndex(
            model_name='emailinterne',
            name='messagerie_email_destinataire_lu_idx',
        ),
        migrations.RenameIndex(
            model_name='emailinterne',
            new_name='messagerie__expedit_56d0a8_idx',
            old_name='messagerie_email_expediteur_brouillon_idx',
        ),
        migrations.RenameIndex(
            model_name='emailinterne',
            new_name='messagerie__importa_178e77_idx',
            old_name='messagerie_email_important_idx',
        ),
        migrations.RemoveField(
            model_name='emailinterne',
            name='destinataire',
        ),
        migrations.RemoveField(
            model_name='emailinterne',
            name='lu',
        ),
        migrations.RemoveField(
            model_name='emailinterne',
            name='supprime_par_destinataire',
        ),
        migrations.AddField(
            model_name='emailinternedestinataire',
            name='destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_recipient_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailinternedestinataire',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_links', to='messagerie.emailinterne'),
        ),
        migrations.AddField(
            model_name='emailinterne',
            name='destinataires',
            field=models.ManyToManyField(blank=True, related_name='emails_recus', through='messagerie.EmailInterneDestinataire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emailinternedestinataire',
            index=models.Index(fields=['destinataire', 'lu', '-date_reception'], name='messagerie__destina_c8619b_idx'),
        ),
        migrations.AddIndex(
            model_name='emailinternedestinataire',
            index=models.Index(fields=['destinataire', 'supprime', '-date_reception'], name='messagerie__destina_078943_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailinternedestinataire',
            unique_together={('email', 'destinataire')},
        ),
    ]
