# Generated by Django 4.2.7 on 2025-11-01 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanificationRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de la planification')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('type_rapport', models.CharField(choices=[('resume_mensuel', 'Résumé Mensuel'), ('statistiques_infractions', 'Statistiques des Infractions'), ('activite_agents', 'Activité des Agents'), ('fiches_ouvertes', 'Fiches Ouvertes'), ('analyse_geographique', 'Analyse Géographique'), ('taux_resolution', 'Taux de Résolution'), ('biometrie', 'Données Biométriques'), ('personnalise', 'Rapport Personnalisé')], max_length=50, verbose_name='Type de rapport')),
                ('format_export', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel (XLSX)'), ('csv', 'CSV'), ('word', 'Word (DOCX)')], max_length=20, verbose_name="Format d'export")),
                ('filtres', models.JSONField(blank=True, default=dict, verbose_name='Filtres à appliquer')),
                ('options_inclusion', models.JSONField(blank=True, default=dict, verbose_name="Options d'inclusion")),
                ('frequence', models.CharField(choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('yearly', 'Annuel')], max_length=50, verbose_name='Fréquence')),
                ('heure_execution', models.TimeField(default='08:00', verbose_name="Heure d'exécution")),
                ('destinataires_emails', models.JSONField(blank=True, default=list, verbose_name='Emails des destinataires')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('derniere_execution', models.DateTimeField(blank=True, null=True, verbose_name='Dernière exécution')),
                ('prochaine_execution', models.DateTimeField(blank=True, null=True, verbose_name='Prochaine exécution')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planifications_rapports', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Planification de rapport',
                'verbose_name_plural': 'Planifications de rapports',
                'db_table': 'planification_rapport',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RapportHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du rapport')),
                ('type_rapport', models.CharField(choices=[('resume_mensuel', 'Résumé Mensuel'), ('statistiques_infractions', 'Statistiques des Infractions'), ('activite_agents', 'Activité des Agents'), ('fiches_ouvertes', 'Fiches Ouvertes'), ('analyse_geographique', 'Analyse Géographique'), ('taux_resolution', 'Taux de Résolution'), ('biometrie', 'Données Biométriques'), ('personnalise', 'Rapport Personnalisé')], max_length=50, verbose_name='Type de rapport')),
                ('format_export', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel (XLSX)'), ('csv', 'CSV'), ('word', 'Word (DOCX)')], max_length=20, verbose_name="Format d'export")),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('filtres', models.JSONField(blank=True, default=dict, verbose_name='Filtres appliqués')),
                ('options_inclusion', models.JSONField(blank=True, default=dict, verbose_name="Options d'inclusion")),
                ('fichier', models.FileField(upload_to='rapports/%Y/%m/%d/', verbose_name='Fichier du rapport')),
                ('taille_fichier', models.IntegerField(default=0, verbose_name='Taille du fichier (octets)')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('erreur', 'Erreur')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('duree_generation', models.FloatField(blank=True, null=True, verbose_name='Durée de génération (secondes)')),
                ('message_erreur', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('nombre_lignes', models.IntegerField(default=0, verbose_name='Nombre de lignes')),
                ('nombre_pages', models.IntegerField(blank=True, null=True, verbose_name='Nombre de pages (PDF/Word)')),
                ('nombre_telechargements', models.IntegerField(default=0, verbose_name='Nombre de téléchargements')),
                ('derniere_consultation', models.DateTimeField(blank=True, null=True, verbose_name='Dernière consultation')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_generes', to=settings.AUTH_USER_MODEL, verbose_name='Généré par')),
            ],
            options={
                'verbose_name': 'Historique de rapport',
                'verbose_name_plural': 'Historiques des rapports',
                'db_table': 'rapport_historique',
                'ordering': ['-date_generation'],
                'indexes': [models.Index(fields=['-date_generation'], name='rapport_his_date_ge_0d2c5e_idx'), models.Index(fields=['utilisateur', '-date_generation'], name='rapport_his_utilisa_55a637_idx'), models.Index(fields=['type_rapport', '-date_generation'], name='rapport_his_type_ra_15257e_idx'), models.Index(fields=['statut'], name='rapport_his_statut_2c8cd2_idx')],
            },
        ),
    ]
