# Generated by Django 4.2.7 on 2025-11-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapporthistorique',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='rapports/%Y/%m/%d/', verbose_name='Fichier du rapport'),
        ),
    ]
