# Generated by Django 4.2.7 on 2025-12-09 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rapports', '0003_alter_planificationrapport_utilisateur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('criminel', 'Rapport Criminel'), ('enquete', "Rapport d'Enquête"), ('statistique', 'Rapport Statistique'), ('audit', "Rapport d'Audit")], db_index=True, max_length=20, verbose_name='Type de rapport')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Paramètres de génération')),
                ('file', models.FileField(blank=True, null=True, upload_to='rapports/%Y/%m/', verbose_name='Fichier du rapport')),
                ('date_generated', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de génération')),
                ('status', models.CharField(choices=[('queued', 'En attente'), ('processing', 'En cours de traitement'), ('done', 'Terminé'), ('error', 'Erreur')], db_index=True, default='queued', max_length=20, verbose_name='Statut')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='Durée de génération (secondes)')),
                ('size_kb', models.IntegerField(blank=True, null=True, verbose_name='Taille du fichier (Ko)')),
                ('archived', models.BooleanField(db_index=True, default=False, verbose_name='Archivé')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Généré par')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'db_table': 'report',
                'ordering': ['-date_generated'],
            },
        ),
        migrations.RemoveField(
            model_name='rapporthistorique',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='PlanificationRapport',
        ),
        migrations.DeleteModel(
            name='RapportHistorique',
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['-date_generated'], name='report_date_ge_3e46bf_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['type', '-date_generated'], name='report_type_8e0903_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='report_status_74972f_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['generated_by', '-date_generated'], name='report_generat_641352_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['archived'], name='report_archive_7ad9b4_idx'),
        ),
    ]
