# Generated by Django 4.2.7 on 2025-12-09 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rapports', '0004_report_remove_rapporthistorique_utilisateur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la planification')),
                ('report_type', models.CharField(choices=[('criminel', 'Rapport Criminel'), ('enquete', "Rapport d'Enquête"), ('statistique', 'Rapport Statistique'), ('audit', "Rapport d'Audit")], db_index=True, max_length=20, verbose_name='Type de rapport')),
                ('frequency', models.CharField(choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('yearly', 'Annuel')], db_index=True, max_length=20, verbose_name='Fréquence')),
                ('default_parameters', models.JSONField(blank=True, default=dict, verbose_name='Paramètres par défaut')),
                ('execution_time', models.TimeField(default='08:00', verbose_name="Heure d'exécution")),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_execution', models.DateTimeField(blank=True, null=True, verbose_name='Dernière exécution')),
                ('next_execution', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Prochaine exécution')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Planification de rapport',
                'verbose_name_plural': 'Planifications de rapports',
                'db_table': 'report_schedule',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'next_execution'], name='report_sche_is_acti_dbed69_idx'), models.Index(fields=['report_type', 'is_active'], name='report_sche_report__1fb216_idx'), models.Index(fields=['frequency', 'is_active'], name='report_sche_frequen_e12c22_idx')],
            },
        ),
    ]
