# Generated by Django 4.2.7 on 2025-12-30 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rapports', '0005_reportschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du rapport')),
                ('type_rapport', models.CharField(choices=[('statistique', 'Rapport Statistique'), ('criminel', 'Rapport Criminel'), ('enquete', "Rapport d'Enquête"), ('audit', "Rapport d'Audit")], db_index=True, max_length=50, verbose_name='Type de rapport')),
                ('parametres', models.JSONField(blank=True, default=dict, verbose_name='Paramètres')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='rapports/%Y/%m/', verbose_name='Fichier')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('erreur', 'Erreur')], db_index=True, default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('date_generation', models.DateTimeField(blank=True, null=True, verbose_name='Date de génération')),
                ('taille_fichier', models.IntegerField(blank=True, null=True, verbose_name='Taille (octets)')),
                ('duree_generation', models.FloatField(blank=True, null=True, verbose_name='Durée (secondes)')),
                ('message_erreur', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'db_table': 'rapport',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.RemoveField(
            model_name='reportschedule',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='ReportSchedule',
        ),
        migrations.AddIndex(
            model_name='rapport',
            index=models.Index(fields=['-date_creation'], name='rapport_date_cr_8a4112_idx'),
        ),
        migrations.AddIndex(
            model_name='rapport',
            index=models.Index(fields=['type_rapport', '-date_creation'], name='rapport_type_ra_a78acb_idx'),
        ),
        migrations.AddIndex(
            model_name='rapport',
            index=models.Index(fields=['statut'], name='rapport_statut_010409_idx'),
        ),
        migrations.AddIndex(
            model_name='rapport',
            index=models.Index(fields=['cree_par', '-date_creation'], name='rapport_cree_pa_1f152d_idx'),
        ),
    ]
