# Generated by Django 4.2.7 on 2025-10-24 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('criminel', '0006_criminalfichecriminelle_date_enregistrement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IAReconnaissanceFaciale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_analysee', models.ImageField(upload_to='ia/reconnaissance/')),
                ('score_confiance', models.FloatField(verbose_name='Score de confiance (%)')),
                ('date_analyse', models.DateTimeField(auto_now_add=True, verbose_name="Date d'analyse")),
                ('statut', models.CharField(choices=[('correspondance_trouvee', 'Correspondance trouvée'), ('aucune_correspondance', 'Aucune correspondance'), ('en_attente', 'En attente de validation')], default='en_attente', max_length=50, verbose_name="Statut de l'analyse")),
                ('analyse_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Analysé par')),
                ('criminel_identifie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats_reconnaissance_ia', to='criminel.criminalfichecriminelle')),
            ],
            options={
                'verbose_name': 'Analyse IA - Reconnaissance faciale',
                'verbose_name_plural': 'Analyses IA - Reconnaissances faciales',
                'db_table': 'ia_reconnaissance_faciale',
                'ordering': ['-date_analyse'],
            },
        ),
        migrations.CreateModel(
            name='IAMatchBiometrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_match', models.CharField(choices=[('visage', 'Reconnaissance faciale'), ('empreinte', 'Reconnaissance dactyloscopique')], max_length=50, verbose_name='Type de correspondance')),
                ('pourcentage_similarite', models.FloatField(verbose_name='Taux de similarité (%)')),
                ('date_detection', models.DateTimeField(auto_now_add=True, verbose_name='Date de détection')),
                ('statut_validation', models.CharField(choices=[('valide', 'Validé'), ('rejete', 'Rejeté'), ('en_attente', 'En attente')], default='en_attente', max_length=50, verbose_name='Statut de validation')),
                ('criminel_correspondant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_correspondants', to='criminel.criminalfichecriminelle')),
                ('criminel_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_source', to='criminel.criminalfichecriminelle')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Correspondance biométrique IA',
                'verbose_name_plural': 'Correspondances biométriques IA',
                'db_table': 'ia_match_biometrique',
                'ordering': ['-date_detection'],
            },
        ),
        migrations.CreateModel(
            name='IAAnalyseStatistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name="Titre de l'analyse")),
                ('description', models.TextField(verbose_name="Description de l'analyse")),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('donnees_source', models.JSONField(verbose_name='Données sources utilisées (JSON)')),
                ('resultat', models.JSONField(verbose_name='Résultats analytiques (JSON)')),
                ('genere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Généré par')),
            ],
            options={
                'verbose_name': 'Analyse statistique IA',
                'verbose_name_plural': 'Analyses statistiques IA',
                'db_table': 'ia_analyse_statistique',
                'ordering': ['-date_generation'],
            },
        ),
    ]
