# Generated by Django 4.2.7 on 2025-10-24 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('criminel', '0006_criminalfichecriminelle_date_enregistrement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intelligence_artificielle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IAPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type_prediction', models.CharField(choices=[('recidive', 'Risque de récidive'), ('zone_risque', 'Zone à risque'), ('profil_dangerosite', 'Profil de dangerosité'), ('association_criminelle', "Probabilité d'association criminelle")], max_length=100, verbose_name='Type de prédiction')),
                ('resultat_prediction', models.JSONField(default=dict)),
                ('score_confiance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('fiche_criminelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='criminel.criminalfichecriminelle')),
                ('genere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analyse prédictive IA',
                'verbose_name_plural': 'Analyses prédictives IA',
                'db_table': 'ia_prediction',
            },
        ),
    ]
