# Generated by Django 4.2.7 on 2025-10-24 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('criminel', '0006_criminalfichecriminelle_date_enregistrement_and_more'),
        ('intelligence_artificielle', '0002_iaprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='IAPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nom_pattern', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_pattern', models.CharField(choices=[('modus_operandi', 'Mode opératoire'), ('zone_criminelle', 'Zone géographique'), ('periode', 'Période temporelle'), ('profil', 'Profil comportemental')], max_length=100, verbose_name='Type de schéma détecté')),
                ('frequence', models.IntegerField(default=0)),
                ('niveau_risque', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('donnees_sources', models.JSONField(blank=True, default=dict)),
                ('date_detection', models.DateTimeField(auto_now_add=True)),
                ('detecte_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schéma criminel détecté',
                'verbose_name_plural': 'Schémas criminels détectés',
                'db_table': 'ia_pattern',
            },
        ),
        migrations.CreateModel(
            name='IACorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type_correlation', models.CharField(choices=[('lieu', 'Même lieu'), ('temps', 'Même période'), ('modus_operandi', 'Même modus operandi'), ('complice', 'Liens de complicité'), ('profil', 'Profil comportemental similaire')], max_length=100, verbose_name='Type de corrélation')),
                ('degre_correlation', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('resume', models.TextField(blank=True, null=True)),
                ('date_detection', models.DateTimeField(auto_now_add=True)),
                ('analyse_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('criminels', models.ManyToManyField(related_name='correlations', to='criminel.criminalfichecriminelle')),
                ('infractions', models.ManyToManyField(blank=True, related_name='correlations', to='criminel.criminalinfraction')),
                ('pattern_associe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correlations', to='intelligence_artificielle.iapattern')),
            ],
            options={
                'verbose_name': 'Corrélation IA',
                'verbose_name_plural': 'Corrélations IA',
                'db_table': 'ia_correlation',
            },
        ),
    ]
