# Generated by Django 4.2.7 on 2025-11-07 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence_artificielle', '0004_iafaceembedding'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='iafaceembedding',
            new_name='ia_face_emb_crimine_22bb29_idx',
            old_name='ia_face_emb_crimine_17dc0d_idx',
        ),
        migrations.RenameIndex(
            model_name='iafaceembedding',
            new_name='ia_face_emb_source__00ce26_idx',
            old_name='ia_face_emb_source__0b1ab7_idx',
        ),
    ]
