# Generated by Django 4.2.7 on 2025-11-08 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intelligence_artificielle', '0005_rename_ia_face_emb_crimine_17dc0d_idx_ia_face_emb_crimine_22bb29_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechercheIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_query', models.ImageField(upload_to='ia/recherches/', verbose_name='Image soumise')),
                ('seuil', models.FloatField(default=0.6, verbose_name='Seuil utilisé')),
                ('top_n', models.PositiveIntegerField(default=3, verbose_name='Nombre de résultats demandés')),
                ('resultats', models.JSONField(default=list, verbose_name='Résultats renvoyés')),
                ('date_recherche', models.DateTimeField(auto_now_add=True, verbose_name='Date de la recherche')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recherches_ia', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Recherche faciale IA',
                'verbose_name_plural': 'Recherches faciales IA',
                'db_table': 'ia_recherche',
                'ordering': ['-date_recherche'],
            },
        ),
    ]
