# Generated by Django 4.2.7 on 2025-11-20 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('criminel', '0017_alter_investigationassignment_assigned_by_and_more'),
        ('intelligence_artificielle', '0007_alter_iaanalysestatistique_genere_par_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IAModelTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nom_modele', models.CharField(max_length=200, verbose_name='Nom du modèle')),
                ('type_modele', models.CharField(choices=[('pattern_recognition', 'Reconnaissance de patterns'), ('prediction', 'Prédiction comportementale'), ('face_recognition', 'Reconnaissance faciale'), ('risk_assessment', 'Évaluation des risques')], max_length=100, verbose_name='Type de modèle')),
                ('parametres_entrainement', models.JSONField(default=dict, verbose_name="Paramètres d'entraînement")),
                ('metriques', models.JSONField(default=dict, help_text='Accuracy, precision, recall, F1-score, etc.', verbose_name='Métriques de performance')),
                ('nb_echantillons', models.IntegerField(default=0, verbose_name="Nombre d'échantillons utilisés")),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('erreur', 'Erreur'), ('annule', 'Annulé')], default='en_cours', max_length=50, verbose_name='Statut')),
                ('chemin_modele', models.CharField(blank=True, max_length=500, null=True, verbose_name='Chemin du modèle sauvegardé')),
                ('version', models.CharField(default='1.0', max_length=50, verbose_name='Version du modèle')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('entraine_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ia_model_trainings', to=settings.AUTH_USER_MODEL, verbose_name='Entraîné par')),
            ],
            options={
                'verbose_name': 'Entraînement de modèle IA',
                'verbose_name_plural': 'Entraînements de modèles IA',
                'db_table': 'ia_model_training',
                'ordering': ['-date_debut'],
                'indexes': [models.Index(fields=['type_modele', '-date_debut'], name='ia_model_tr_type_mo_186e4d_idx'), models.Index(fields=['statut'], name='ia_model_tr_statut_b4aa1a_idx')],
            },
        ),
        migrations.CreateModel(
            name='IAFaceDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image_source', models.ImageField(upload_to='ia/detections/', verbose_name='Image source')),
                ('bbox_x', models.FloatField(verbose_name='X (coordonnée gauche)')),
                ('bbox_y', models.FloatField(verbose_name='Y (coordonnée haut)')),
                ('bbox_width', models.FloatField(verbose_name='Largeur')),
                ('bbox_height', models.FloatField(verbose_name='Hauteur')),
                ('facial_landmarks', models.JSONField(blank=True, default=list, help_text='Liste de points [x, y] pour les landmarks faciaux', verbose_name='Points faciaux')),
                ('embedding', models.JSONField(blank=True, default=list, help_text="Vecteur d'encodage facial (512 dimensions)", verbose_name='Embedding facial')),
                ('matches', models.JSONField(blank=True, default=list, help_text='Liste des correspondances trouvées avec scores', verbose_name='Correspondances')),
                ('confidence_detection', models.FloatField(default=0.0, verbose_name='Confiance de détection')),
                ('age_estime', models.IntegerField(blank=True, null=True, verbose_name='Âge estimé')),
                ('genre_estime', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('U', 'Indéterminé')], default='U', max_length=10, verbose_name='Genre estimé')),
                ('date_detection', models.DateTimeField(auto_now_add=True, verbose_name='Date de détection')),
                ('recherche_ia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_detections', to='intelligence_artificielle.rechercheia', verbose_name='Recherche IA associée')),
            ],
            options={
                'verbose_name': 'Détection faciale IA',
                'verbose_name_plural': 'Détections faciales IA',
                'db_table': 'ia_face_detection',
                'ordering': ['-date_detection'],
                'indexes': [models.Index(fields=['-date_detection'], name='ia_face_det_date_de_11f6d6_idx'), models.Index(fields=['recherche_ia'], name='ia_face_det_recherc_84a1e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='IACaseAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type_analyse', models.CharField(choices=[('complet', 'Analyse complète'), ('recidive', 'Risque de récidive'), ('dangerosite', 'Profil de dangerosité'), ('zones_risque', 'Zones à risque'), ('associations', 'Associations criminelles'), ('comportement', 'Prédiction comportementale')], default='complet', max_length=100, verbose_name="Type d'analyse")),
                ('resultats', models.JSONField(default=dict, help_text="Résultats détaillés de l'analyse prédictive", verbose_name="Résultats de l'analyse")),
                ('score_risque_global', models.FloatField(default=0.0, verbose_name='Score de risque global (0-100)')),
                ('score_confiance', models.FloatField(default=0.0, verbose_name='Score de confiance de la prédiction (0-100)')),
                ('liens_detectes', models.JSONField(blank=True, default=list, help_text='Liste des liens entre suspects détectés', verbose_name='Liens détectés')),
                ('recommandations', models.JSONField(blank=True, default=list, help_text="Recommandations basées sur l'analyse", verbose_name='Recommandations')),
                ('model_version', models.CharField(default='1.0', max_length=50, verbose_name='Version du modèle utilisé')),
                ('features_utilisees', models.JSONField(blank=True, default=list, help_text="Liste des features utilisées pour l'analyse", verbose_name='Features utilisées')),
                ('date_analyse', models.DateTimeField(auto_now_add=True, verbose_name="Date d'analyse")),
                ('analyse_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ia_case_analyses', to=settings.AUTH_USER_MODEL, verbose_name='Analysé par')),
                ('fiche_criminelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_case_analyses', to='criminel.criminalfichecriminelle', verbose_name='Fiche criminelle')),
            ],
            options={
                'verbose_name': 'Analyse de dossier IA',
                'verbose_name_plural': 'Analyses de dossiers IA',
                'db_table': 'ia_case_analysis',
                'ordering': ['-date_analyse'],
                'indexes': [models.Index(fields=['fiche_criminelle', '-date_analyse'], name='ia_case_ana_fiche_c_9467d7_idx'), models.Index(fields=['type_analyse'], name='ia_case_ana_type_an_506884_idx'), models.Index(fields=['-score_risque_global'], name='ia_case_ana_score_r_602f08_idx')],
            },
        ),
    ]
