# Generated by Django 4.2.7 on 2025-11-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence_artificielle', '0008_add_face_detection_and_case_analysis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IAFaceDetection',
        ),
    ]
