# Generated by Django 4.2.7 on 2025-11-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence_artificielle', '0009_remove_face_detection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iamodeltraining',
            name='type_modele',
            field=models.CharField(choices=[('prediction', 'Prédiction comportementale'), ('face_recognition', 'Reconnaissance faciale'), ('risk_assessment', 'Évaluation des risques')], max_length=100, verbose_name='Type de modèle'),
        ),
    ]
