# Generated by Django 4.2.7 on 2025-11-14 17:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import enquete.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('criminel', '0014_add_overdue_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportEnquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('date_redaction', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('valide', 'Validé')], default='brouillon', max_length=20)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_enquete', to='criminel.criminalfichecriminelle')),
                ('enqueteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_enquete', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_redaction',),
            },
        ),
        migrations.CreateModel(
            name='Preuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_preuve', models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo'), ('document', 'Document'), ('objet', 'Objet')], max_length=20)),
                ('fichier', models.FileField(upload_to=enquete.models.preuve_upload_path)),
                ('description', models.TextField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preuves', to='criminel.criminalfichecriminelle')),
                ('enqueteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preuves_enregistrements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_ajout',),
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations_enquete', to='criminel.criminalfichecriminelle')),
                ('enqueteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations_enregistrements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Avancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('commentaire', models.TextField(blank=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avancement_enquete', to='criminel.criminalfichecriminelle')),
                ('enqueteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avancements_enquete', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_mise_a_jour',),
            },
        ),
    ]
