# Generated by Django 4.2.7 on 2025-11-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preuve',
            name='type_preuve',
            field=models.CharField(choices=[('photo', 'Photo'), ('document', 'Document')], max_length=20),
        ),
    ]
