# Generated by Django 4.2.7 on 2026-01-20 00:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import enquete.models
import enquete.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('criminel', '0024_alter_criminalinfraction_statut_affaire_and_more'),
        ('upr', '0008_add_face_encoding_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquete', '0003_alter_avancement_enqueteur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEnquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('consultation', 'Consultation'), ('cloture', 'Clôture'), ('reouverture', 'Réouverture'), ('ajout_preuve', 'Ajout de preuve'), ('suppression_preuve', 'Suppression de preuve'), ('ajout_rapport', 'Ajout de rapport'), ('validation_rapport', 'Validation de rapport'), ('ajout_personne', 'Ajout de personne'), ('ajout_infraction', "Ajout d'infraction"), ('modification_statut', 'Modification de statut'), ('export', 'Export'), ('impression', 'Impression'), ('autre', 'Autre')], max_length=50, verbose_name='Action')),
                ('description', models.TextField(help_text="Description détaillée de l'action", verbose_name='Description')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('details', models.JSONField(blank=True, help_text="Détails supplémentaires de l'action au format JSON", null=True, verbose_name='Détails supplémentaires')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
            ],
            options={
                'verbose_name': "Journal d'audit d'enquête",
                'verbose_name_plural': "Journaux d'audit d'enquête",
                'db_table': 'enquete_audit_log_enquete',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='BiometrieEnquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_judiciaire', models.ImageField(blank=True, null=True, upload_to='enquetes/biometrie/photos/%Y/%m/', verbose_name='Photo judiciaire')),
                ('empreintes_digitales', models.FileField(blank=True, null=True, upload_to='enquetes/biometrie/empreintes/%Y/%m/', verbose_name='Empreintes digitales')),
                ('resultat_reconnaissance', models.JSONField(blank=True, help_text='Résultats de la reconnaissance faciale (matches, scores, etc.)', null=True, verbose_name='Résultat reconnaissance faciale')),
                ('score_similarite_ia', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Score de similarité IA (%)')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': "Données biométriques d'enquête",
                'verbose_name_plural': "Données biométriques d'enquête",
                'db_table': 'enquete_biometrie_enquete',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='DecisionCloture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion', models.TextField(help_text="Conclusion et résumé de l'enquête", verbose_name="Conclusion de l'enquête")),
                ('decision_judiciaire', models.TextField(blank=True, help_text="Décision prise par l'autorité judiciaire", null=True, verbose_name='Décision judiciaire')),
                ('date_cloture', models.DateTimeField(auto_now_add=True, verbose_name='Date de clôture')),
                ('fichier_decision', models.FileField(blank=True, null=True, upload_to='enquetes/decisions/%Y/%m/', verbose_name='Fichier de décision')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Décision de clôture',
                'verbose_name_plural': 'Décisions de clôture',
                'db_table': 'enquete_decision_cloture',
            },
        ),
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique')),
                ('numero_enquete', models.CharField(help_text='Numéro unique généré automatiquement', max_length=50, unique=True, verbose_name="Numéro d'enquête")),
                ('type_infraction', models.CharField(blank=True, help_text="Type d'infraction concernée par l'enquête", max_length=200, null=True, verbose_name="Type d'infraction")),
                ('type_enquete_code', models.CharField(choices=[('plainte', 'Plainte'), ('denonciation', 'Dénonciation'), ('constatation_directe', 'Constatation directe')], help_text="Type d'enquête: Plainte, Dénonciation ou Constatation directe", max_length=50, verbose_name="Type d'enquête (code)")),
                ('titre', models.CharField(max_length=255, verbose_name="Titre de l'enquête")),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('lieu', models.CharField(blank=True, max_length=255, null=True, verbose_name="Lieu de l'incident")),
                ('date_incident', models.DateTimeField(blank=True, null=True, verbose_name="Date de l'incident")),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('date_ouverture', models.DateTimeField(auto_now_add=True, help_text="Date d'ouverture de l'enquête", verbose_name="Date d'ouverture")),
                ('date_cloture', models.DateTimeField(blank=True, help_text="Date de clôture de l'enquête (si clôturée)", null=True, verbose_name='Date de clôture')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('suspendue', 'Suspendue'), ('cloturee', 'Clôturée'), ('classee', 'Classée')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('priorite', models.CharField(choices=[('faible', 'Faible'), ('normale', 'Normale'), ('elevee', 'Élevée'), ('urgente', 'Urgente')], default='normale', max_length=20, verbose_name='Priorité')),
                ('plaignant_nom', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du plaignant')),
                ('plaignant_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact du plaignant')),
                ('denonciateur_nom', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du dénonciateur')),
                ('denonciateur_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact du dénonciateur')),
                ('source_denonciation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Source de la dénonciation')),
                ('constatateur_nom', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du constatateur')),
                ('unite_constatation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Unité de constatation')),
                ('circonstances', models.TextField(blank=True, null=True, verbose_name='Circonstances de la constatation')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes complémentaires')),
            ],
            options={
                'verbose_name': 'Enquête',
                'verbose_name_plural': 'Enquêtes',
                'db_table': 'enquete_enquete',
                'ordering': ['-date_enregistrement'],
            },
        ),
        migrations.CreateModel(
            name='EnqueteCriminel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text="Rôle du criminel dans l'enquête (ex: suspect, témoin, victime)", max_length=100, null=True, verbose_name='Rôle')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('notes', models.TextField(blank=True, help_text="Notes complémentaires sur le lien entre l'enquête et le criminel", null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Relation Enquête-Criminel',
                'verbose_name_plural': 'Relations Enquête-Criminel',
                'db_table': 'enquete_enquete_criminel',
            },
        ),
        migrations.CreateModel(
            name='InfractionEnquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_juridique', models.CharField(help_text='Ex: Vol aggravé, Homicide volontaire, etc.', max_length=500, verbose_name='Qualification juridique')),
                ('articles_loi', models.TextField(help_text='Articles de loi applicables (Code pénal, Code de procédure pénale, etc.)', verbose_name='Articles de loi')),
                ('date_faits', models.DateTimeField(verbose_name='Date des faits')),
                ('lieu_faits', models.CharField(help_text='Lieu précis où les faits se sont déroulés', max_length=500, verbose_name='Lieu des faits')),
                ('description_faits', models.TextField(help_text='Description détaillée des faits', verbose_name='Description des faits')),
                ('degre_gravite', models.CharField(choices=[('contravention', 'Contravention'), ('delit', 'Délit'), ('crime', 'Crime')], default='delit', max_length=50, verbose_name='Degré de gravité')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': "Infraction liée à l'enquête",
                'verbose_name_plural': 'Infractions liées aux enquêtes',
                'db_table': 'enquete_infraction_enquete',
                'ordering': ['-date_faits'],
            },
        ),
        migrations.CreateModel(
            name='PersonneEnquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('suspect', 'Suspect'), ('victime', 'Victime'), ('temoin', 'Témoin'), ('plaignant', 'Plaignant'), ('autre', 'Autre')], max_length=50, verbose_name="Rôle dans l'enquête")),
                ('nom', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=200, null=True, verbose_name='Prénom')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu de naissance')),
                ('nationalite', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationalité')),
                ('numero_identite', models.CharField(blank=True, max_length=50, null=True, verbose_name="Numéro d'identité")),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('lien_enquete', models.TextField(blank=True, help_text="Décrire le lien de cette personne avec l'enquête", null=True, verbose_name="Lien avec l'enquête")),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': "Personne liée à l'enquête",
                'verbose_name_plural': 'Personnes liées aux enquêtes',
                'db_table': 'enquete_personne_enquete',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='PreuveEnquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_scelle', models.CharField(help_text='Numéro unique de scellé généré automatiquement', max_length=100, unique=True, verbose_name='Numéro de scellé')),
                ('type_preuve', models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo'), ('audio', 'Audio'), ('document', 'Document'), ('objet', 'Objet'), ('autre', 'Autre')], max_length=50, verbose_name='Type de preuve')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_collecte', models.DateTimeField(verbose_name='Date et heure de collecte')),
                ('lieu_collecte', models.CharField(max_length=500, verbose_name='Lieu de collecte')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='enquetes/preuves/%Y/%m/', verbose_name='Fichier')),
                ('hash_sha256', models.CharField(blank=True, help_text="Hash du fichier pour vérification d'intégrité", max_length=64, null=True, verbose_name='Hash SHA256')),
                ('est_scelle', models.BooleanField(default=False, help_text='Indique si la preuve est scellée', verbose_name='Scellé')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': "Preuve d'enquête",
                'verbose_name_plural': "Preuves d'enquête",
                'db_table': 'enquete_preuve_enquete',
                'ordering': ['-date_collecte'],
            },
        ),
        migrations.CreateModel(
            name='RapportEnqueteComplet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rapport', models.CharField(choices=[('pv_audition', "PV d'audition"), ('rapport_intervention', "Rapport d'intervention"), ('rapport_technique', 'Rapport technique'), ('rapport_analyse_ia', "Rapport d'analyse IA"), ('autre', 'Autre')], max_length=50, verbose_name='Type de rapport')),
                ('titre', models.CharField(max_length=500, verbose_name='Titre')),
                ('contenu', models.TextField(help_text='Contenu du rapport ou PV', verbose_name='Contenu')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='enquetes/rapports/%Y/%m/', verbose_name='Fichier')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='brouillon', max_length=50, verbose_name='Statut')),
                ('date_redaction', models.DateTimeField(auto_now_add=True, verbose_name='Date de rédaction')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
            ],
            options={
                'verbose_name': "Rapport d'enquête",
                'verbose_name_plural': "Rapports d'enquête",
                'db_table': 'enquete_rapport_enquete_complet',
                'ordering': ['-date_redaction'],
            },
        ),
        migrations.CreateModel(
            name='RapportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Type de rapport',
                'verbose_name_plural': 'Types de rapport',
                'db_table': 'enquete_rapport_type',
            },
        ),
        migrations.CreateModel(
            name='TypeEnquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('couleur', models.CharField(default='#6c757d', help_text="Couleur hexadécimale pour l'affichage", max_length=7)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Type d'enquête",
                'verbose_name_plural': "Types d'enquête",
                'db_table': 'enquete_type_enquete',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.AlterField(
            model_name='preuve',
            name='dossier',
            field=models.ForeignKey(blank=True, help_text='Dossier criminel associé (si pas lié à une enquête)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preuves', to='criminel.criminalfichecriminelle', verbose_name='Dossier criminel'),
        ),
        migrations.AlterField(
            model_name='preuve',
            name='fichier',
            field=models.FileField(upload_to=enquete.models.preuve_upload_path, validators=[enquete.validators.validate_preuve_file_size, enquete.validators.validate_preuve_file_type]),
        ),
        migrations.AlterField(
            model_name='rapportenquete',
            name='dossier',
            field=models.ForeignKey(blank=True, help_text='Dossier criminel associé (si pas lié à une enquête)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapports_enquete', to='criminel.criminalfichecriminelle', verbose_name='Dossier criminel'),
        ),
        migrations.AddIndex(
            model_name='typeenquete',
            index=models.Index(fields=['code'], name='enquete_typ_code_235357_idx'),
        ),
        migrations.AddIndex(
            model_name='typeenquete',
            index=models.Index(fields=['actif'], name='enquete_typ_actif_41fc71_idx'),
        ),
        migrations.AddField(
            model_name='rapportenquetecomplet',
            name='enquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_complets', to='enquete.enquete', verbose_name='Enquête'),
        ),
        migrations.AddField(
            model_name='rapportenquetecomplet',
            name='redacteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_enquetes_rediges', to=settings.AUTH_USER_MODEL, verbose_name='Rédacteur'),
        ),
        migrations.AddField(
            model_name='rapportenquetecomplet',
            name='type_rapport_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports', to='enquete.rapporttype', verbose_name='Type de rapport (détaillé)'),
        ),
        migrations.AddField(
            model_name='rapportenquetecomplet',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_enquetes_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='preuveenquete',
            name='agent_collecteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preuves_collectees', to=settings.AUTH_USER_MODEL, verbose_name='Agent collecteur'),
        ),
        migrations.AddField(
            model_name='preuveenquete',
            name='ajoute_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preuves_enquetes_ajoutees', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par'),
        ),
        migrations.AddField(
            model_name='preuveenquete',
            name='enquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preuves_enquete', to='enquete.enquete', verbose_name='Enquête'),
        ),
        migrations.AddField(
            model_name='personneenquete',
            name='ajoute_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnes_enquetes_ajoutees', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par'),
        ),
        migrations.AddField(
            model_name='personneenquete',
            name='enquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnes', to='enquete.enquete', verbose_name='Enquête'),
        ),
        migrations.AddField(
            model_name='personneenquete',
            name='fiche_criminelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnes_enquetes', to='criminel.criminalfichecriminelle', verbose_name='Fiche criminelle'),
        ),
        migrations.AddField(
            model_name='personneenquete',
            name='upr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnes_enquetes', to='upr.unidentifiedperson', verbose_name='Personne non identifiée (UPR)'),
        ),
        migrations.AddField(
            model_name='infractionenquete',
            name='ajoute_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infractions_enquetes_ajoutees', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par'),
        ),
        migrations.AddField(
            model_name='infractionenquete',
            name='enquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infractions', to='enquete.enquete', verbose_name='Enquête'),
        ),
        migrations.AddField(
            model_name='enquetecriminel',
            name='ajoute_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par'),
        ),
        migrations.AddField(
            model_name='enquetecriminel',
            name='criminel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquetes_liees', to='criminel.criminalfichecriminelle', verbose_name='Criminel (Fiche criminelle)'),
        ),
        migrations.AddField(
            model_name='enquetecriminel',
            name='enquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criminels_lies', to='enquete.enquete', verbose_name='Enquête'),
        ),
        migrations.AddField(
            model_name='enquete',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquetes_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='enquete',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquetes', to='criminel.criminalfichecriminelle', verbose_name='Dossier criminel associé'),
        ),
        migrations.AddField(
            model_name='enquete',
            name='enqueteur_principal',
            field=models.ForeignKey(blank=True, help_text='Enquêteur principal (synonyme de enqueteur_responsable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquetes_principales', to=settings.AUTH_USER_MODEL, verbose_name='Enquêteur principal'),
        ),
        migrations.AddField(
            model_name='enquete',
            name='enqueteur_responsable',
            field=models.ForeignKey(blank=True, help_text="Enquêteur responsable de l'enquête (alias enqueteur_principal)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquetes_responsables', to=settings.AUTH_USER_MODEL, verbose_name='Enquêteur responsable'),
        ),
        migrations.AddField(
            model_name='enquete',
            name='enqueteurs_associes',
            field=models.ManyToManyField(blank=True, related_name='enquetes_associees', to=settings.AUTH_USER_MODEL, verbose_name='Enquêteurs associés'),
        ),
        migrations.AddField(
            model_name='enquete',
            name='type_enquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquetes', to='enquete.typeenquete', verbose_name="Type d'enquête"),
        ),
        migrations.AddField(
            model_name='decisioncloture',
            name='autorite_validatrice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_cloture_validees', to=settings.AUTH_USER_MODEL, verbose_name='Autorité validatrice'),
        ),
        migrations.AddField(
            model_name='decisioncloture',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_cloture_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='decisioncloture',
            name='enquete',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision_cloture', to='enquete.enquete', verbose_name='Enquête'),
        ),
        migrations.AddField(
            model_name='biometrieenquete',
            name='ajoute_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometrie_enquetes_ajoutee', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par'),
        ),
        migrations.AddField(
            model_name='biometrieenquete',
            name='enquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donnees_biometriques', to='enquete.enquete', verbose_name='Enquête'),
        ),
        migrations.AddField(
            model_name='biometrieenquete',
            name='personne_enquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donnees_biometriques', to='enquete.personneenquete', verbose_name='Personne'),
        ),
        migrations.AddField(
            model_name='auditlogenquete',
            name='enquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='enquete.enquete', verbose_name='Enquête'),
        ),
        migrations.AddField(
            model_name='auditlogenquete',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_enquetes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='preuve',
            name='enquete',
            field=models.ForeignKey(blank=True, help_text='Enquête associée à cette preuve', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preuves', to='enquete.enquete', verbose_name='Enquête'),
        ),
        migrations.AddField(
            model_name='rapportenquete',
            name='enquete',
            field=models.ForeignKey(blank=True, help_text='Enquête associée à ce rapport', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapports_enquete', to='enquete.enquete', verbose_name='Enquête'),
        ),
        migrations.AddIndex(
            model_name='rapportenquetecomplet',
            index=models.Index(fields=['enquete', '-date_redaction'], name='enquete_rap_enquete_dd5401_idx'),
        ),
        migrations.AddIndex(
            model_name='rapportenquetecomplet',
            index=models.Index(fields=['type_rapport'], name='enquete_rap_type_ra_a7f73a_idx'),
        ),
        migrations.AddIndex(
            model_name='rapportenquetecomplet',
            index=models.Index(fields=['statut'], name='enquete_rap_statut_425bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='preuveenquete',
            index=models.Index(fields=['enquete', '-date_collecte'], name='enquete_pre_enquete_52459b_idx'),
        ),
        migrations.AddIndex(
            model_name='preuveenquete',
            index=models.Index(fields=['numero_scelle'], name='enquete_pre_numero__039501_idx'),
        ),
        migrations.AddIndex(
            model_name='preuveenquete',
            index=models.Index(fields=['type_preuve'], name='enquete_pre_type_pr_59c3a6_idx'),
        ),
        migrations.AddIndex(
            model_name='preuveenquete',
            index=models.Index(fields=['hash_sha256'], name='enquete_pre_hash_sh_1e8138_idx'),
        ),
        migrations.AddIndex(
            model_name='personneenquete',
            index=models.Index(fields=['enquete', 'role'], name='enquete_per_enquete_e64830_idx'),
        ),
        migrations.AddIndex(
            model_name='personneenquete',
            index=models.Index(fields=['fiche_criminelle'], name='enquete_per_fiche_c_253459_idx'),
        ),
        migrations.AddIndex(
            model_name='personneenquete',
            index=models.Index(fields=['upr'], name='enquete_per_upr_id_293644_idx'),
        ),
        migrations.AddIndex(
            model_name='infractionenquete',
            index=models.Index(fields=['enquete', '-date_faits'], name='enquete_inf_enquete_7a3f23_idx'),
        ),
        migrations.AddIndex(
            model_name='infractionenquete',
            index=models.Index(fields=['degre_gravite'], name='enquete_inf_degre_g_c1cb10_idx'),
        ),
        migrations.AddIndex(
            model_name='enquetecriminel',
            index=models.Index(fields=['enquete', 'criminel'], name='enquete_enq_enquete_e42e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='enquetecriminel',
            index=models.Index(fields=['-date_ajout'], name='enquete_enq_date_aj_91eb9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enquetecriminel',
            unique_together={('enquete', 'criminel')},
        ),
        migrations.AddIndex(
            model_name='enquete',
            index=models.Index(fields=['numero_enquete'], name='enquete_enq_numero__5dcf80_idx'),
        ),
        migrations.AddIndex(
            model_name='enquete',
            index=models.Index(fields=['type_enquete_code', '-date_enregistrement'], name='enquete_enq_type_en_dbf0ea_idx'),
        ),
        migrations.AddIndex(
            model_name='enquete',
            index=models.Index(fields=['statut', '-date_enregistrement'], name='enquete_enq_statut_acdd89_idx'),
        ),
        migrations.AddIndex(
            model_name='enquete',
            index=models.Index(fields=['enqueteur_principal', '-date_enregistrement'], name='enquete_enq_enquete_4dc9a7_idx'),
        ),
        migrations.AddIndex(
            model_name='biometrieenquete',
            index=models.Index(fields=['enquete', '-date_ajout'], name='enquete_bio_enquete_557448_idx'),
        ),
        migrations.AddIndex(
            model_name='biometrieenquete',
            index=models.Index(fields=['personne_enquete'], name='enquete_bio_personn_a0f0a0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogenquete',
            index=models.Index(fields=['enquete', '-date_action'], name='enquete_aud_enquete_78425a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogenquete',
            index=models.Index(fields=['utilisateur', '-date_action'], name='enquete_aud_utilisa_d5478a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogenquete',
            index=models.Index(fields=['action'], name='enquete_aud_action_f04ccc_idx'),
        ),
    ]
