# Generated by Django 4.2.7 on 2026-01-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0007_ajouter_sous_categories_types_enquete'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='preuve',
            index=models.Index(fields=['enquete', '-date_ajout'], name='enquete_pre_enquete_c1000c_idx'),
        ),
        migrations.AddIndex(
            model_name='preuve',
            index=models.Index(fields=['dossier', '-date_ajout'], name='enquete_pre_dossier_137a63_idx'),
        ),
        migrations.AddIndex(
            model_name='rapportenquete',
            index=models.Index(fields=['enquete', '-date_redaction'], name='enquete_rap_enquete_be0c72_idx'),
        ),
        migrations.AddIndex(
            model_name='rapportenquete',
            index=models.Index(fields=['dossier', '-date_redaction'], name='enquete_rap_dossier_054bd8_idx'),
        ),
    ]
