# Generated by Django 4.2.7 on 2026-03-18 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enquete.models
import enquete.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquete', '0008_preuve_enquete_pre_enquete_c1000c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEnquete',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Nom descriptif du document', max_length=255, verbose_name='Nom du document')),
                ('type_document', models.CharField(choices=[('excel', 'Excel'), ('word', 'Word'), ('pdf', 'PDF'), ('powerpoint', 'PowerPoint'), ('image', 'Image'), ('csv', 'CSV / Tableur'), ('archive', 'Archive (ZIP/RAR)'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Type de document')),
                ('fichier', models.FileField(upload_to=enquete.models.document_enquete_upload_path, validators=[enquete.validators.validate_document_file_size, enquete.validators.validate_document_file_type], verbose_name='Fichier')),
                ('taille_fichier', models.BigIntegerField(default=0, verbose_name='Taille (octets)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ajoute_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ajoute par')),
                ('enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='enquete.enquete', verbose_name='Enquete')),
            ],
            options={
                'verbose_name': "Document d'enquete",
                'verbose_name_plural': "Documents d'enquete",
                'db_table': 'enquete_document',
                'ordering': ['-date_ajout'],
                'indexes': [models.Index(fields=['enquete', '-date_ajout'], name='enquete_doc_enquete_ec3404_idx'), models.Index(fields=['type_document'], name='enquete_doc_type_do_4b2893_idx')],
            },
        ),
    ]
