# Generated by Django 4.2.7 on 2026-03-18 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0009_documentenquete'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documentenquete',
            name='enquete_doc_enquete_ec3404_idx',
        ),
        migrations.AddField(
            model_name='documentenquete',
            name='categorie',
            field=models.CharField(choices=[('judiciaire', 'Enquete judiciaire'), ('criminelle', 'Enquete criminelle'), ('criminologique', 'Enquete criminologique'), ('numerique', 'Enquete numerique'), ('renseignement', 'Enquete de renseignement'), ('terrain', 'Enquete de terrain'), ('scientifique', 'Enquete scientifique'), ('financiere', 'Enquete financiere'), ('mixte', 'Enquete mixte')], db_index=True, default='mixte', max_length=30, verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='documentenquete',
            name='enquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='enquete.enquete', verbose_name='Enquete'),
        ),
        migrations.AlterField(
            model_name='documentenquete',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom du document'),
        ),
        migrations.AddIndex(
            model_name='documentenquete',
            index=models.Index(fields=['categorie', '-date_ajout'], name='enquete_doc_categor_c46ff6_idx'),
        ),
    ]
