# Generated by Django 4.2.7 on 2026-03-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0010_remove_documentenquete_enquete_doc_enquete_ec3404_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquete',
            name='source_denonciation',
            field=models.CharField(blank=True, choices=[('anonyme', 'Anonyme'), ('telephone', 'Téléphone'), ('courrier', 'Courrier'), ('en_personne', 'En personne'), ('en_ligne', 'En ligne'), ('autre', 'Autre')], max_length=100, null=True, verbose_name='Source de la dénonciation'),
        ),
        migrations.AlterField(
            model_name='enquetecriminel',
            name='role',
            field=models.CharField(choices=[('suspect', 'Suspect'), ('complice', 'Complice'), ('temoin', 'Témoin'), ('victime', 'Victime'), ('informateur', 'Informateur'), ('mis_en_cause', 'Mis en cause'), ('autre', 'Autre')], default='suspect', help_text="Rôle du criminel dans l'enquête", max_length=100, verbose_name='Rôle'),
        ),
    ]
