# Generated by Django 5.2.7 on 2025-10-20 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefStatutAffaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0)),
                ('couleur', models.CharField(default='#6c757d', help_text='Couleur hexadécimale', max_length=7)),
            ],
            options={
                'verbose_name': "Statut d'affaire",
                'verbose_name_plural': "Statuts d'affaires",
                'db_table': 'ref_statut_affaire',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='RefStatutFiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Statut de fiche',
                'verbose_name_plural': 'Statuts de fiches',
                'db_table': 'ref_statut_fiche',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='RefTypeInfraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('categorie', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': "Type d'infraction",
                'verbose_name_plural': "Types d'infractions",
                'db_table': 'ref_type_infraction',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='CriminalFicheCriminelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fiche', models.CharField(max_length=50, unique=True, verbose_name='Numéro de fiche')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=10)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='criminels/photos/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('statut_fiche', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_criminelles', to='criminel.refstatutfiche')),
            ],
            options={
                'verbose_name': 'Fiche criminelle',
                'verbose_name_plural': 'Fiches criminelles',
                'db_table': 'criminal_fiche_criminelle',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CriminalTypeInfraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('gravite', models.IntegerField(default=1, help_text='Niveau de gravité de 1 à 10')),
                ('description', models.TextField(blank=True, null=True)),
                ('peine_minimale', models.CharField(blank=True, max_length=100, null=True)),
                ('peine_maximale', models.CharField(blank=True, max_length=100, null=True)),
                ('article_loi', models.CharField(blank=True, help_text="Référence de l'article de loi", max_length=50, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('couleur', models.CharField(default='#6c757d', help_text="Couleur hexadécimale pour l'affichage", max_length=7)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('type_infraction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types_infractions_detailles', to='criminel.reftypeinfraction')),
            ],
            options={
                'verbose_name': "Type d'infraction détaillé",
                'verbose_name_plural': "Types d'infractions détaillés",
                'db_table': 'criminal_type_infraction',
                'ordering': ['-gravite', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='CriminalInfraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_infraction', models.DateField()),
                ('lieu', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infractions', to='criminel.criminalfichecriminelle')),
                ('type_infraction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infractions', to='criminel.criminaltypeinfraction')),
                ('statut_affaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infractions', to='criminel.refstatutaffaire')),
            ],
            options={
                'verbose_name': 'Infraction',
                'verbose_name_plural': 'Infractions',
                'db_table': 'criminal_infraction',
                'ordering': ['-date_infraction'],
                'indexes': [models.Index(fields=['fiche', '-date_infraction'], name='criminal_in_fiche_i_733b3c_idx'), models.Index(fields=['date_infraction'], name='criminal_in_date_in_06a645_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='criminalfichecriminelle',
            index=models.Index(fields=['numero_fiche'], name='criminal_fi_numero__aa6494_idx'),
        ),
        migrations.AddIndex(
            model_name='criminalfichecriminelle',
            index=models.Index(fields=['nom', 'prenom'], name='criminal_fi_nom_fc6378_idx'),
        ),
        migrations.AddIndex(
            model_name='criminalfichecriminelle',
            index=models.Index(fields=['-date_creation'], name='criminal_fi_date_cr_9ada78_idx'),
        ),
        migrations.AddIndex(
            model_name='criminaltypeinfraction',
            index=models.Index(fields=['code'], name='criminal_ty_code_1f50ad_idx'),
        ),
        migrations.AddIndex(
            model_name='criminaltypeinfraction',
            index=models.Index(fields=['gravite'], name='criminal_ty_gravite_c52a21_idx'),
        ),
    ]
