# Generated by Django 4.2.7 on 2025-10-21 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criminel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='antecedent_judiciaire',
            field=models.TextField(blank=True, null=True, verbose_name='Antécédent judiciaire'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='barbe',
            field=models.CharField(blank=True, choices=[('aucune', 'Aucune'), ('courte', 'Courte'), ('longue', 'Longue'), ('moustache', 'Moustache'), ('bouc', 'Bouc')], max_length=50, null=True, verbose_name='Barbe/Moustache'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='cheveux',
            field=models.CharField(blank=True, choices=[('noirs', 'Noirs'), ('bruns', 'Bruns'), ('chatains', 'Châtains'), ('blonds', 'Blonds'), ('roux', 'Roux'), ('gris', 'Gris'), ('blancs', 'Blancs'), ('chauves', 'Chauves')], max_length=50, null=True, verbose_name='Cheveux'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='cin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="CIN (Carte d'Identité Nationale)"),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact/Téléphone'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='corpulence',
            field=models.CharField(blank=True, choices=[('mince', 'Mince'), ('normale', 'Normale'), ('forte', 'Forte'), ('obese', 'Obèse')], max_length=50, null=True, verbose_name='Corpulence'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='date_arrestation',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'arrestation"),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='lieu_arrestation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Lieu d'arrestation"),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu de naissance'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='marques_particulieres',
            field=models.TextField(blank=True, null=True, verbose_name='Marque(s) particulière(s)'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='motif_arrestation',
            field=models.TextField(blank=True, null=True, verbose_name="Motif de l'arrestation"),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='nationalite',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationalité'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='nom_mere',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de la mère'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='nom_pere',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du père'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='peine_encourue',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Peine encourue'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='reference_pv',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence P.V (Procès-Verbal)'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='service_militaire',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Service militaire'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='suite_judiciaire',
            field=models.TextField(blank=True, null=True, verbose_name='Suite judiciaire'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='surnom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Surnom/Alias'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='unite_saisie',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Unité saisie de l'affaire"),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='visage',
            field=models.CharField(blank=True, choices=[('ovale', 'Ovale'), ('rond', 'Rond'), ('carre', 'Carré'), ('allonge', 'Allongé'), ('triangulaire', 'Triangulaire')], max_length=50, null=True, verbose_name='Forme du visage'),
        ),
        migrations.AlterField(
            model_name='criminalfichecriminelle',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='criminalfichecriminelle',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='criminalfichecriminelle',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='criminalfichecriminelle',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='criminalfichecriminelle',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='criminalfichecriminelle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='criminels/photos/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='criminalfichecriminelle',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='criminalfichecriminelle',
            name='sexe',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=10, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='criminalfichecriminelle',
            name='statut_fiche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_criminelles', to='criminel.refstatutfiche', verbose_name='Statut de la fiche'),
        ),
    ]
