# Generated by Django 4.2.7 on 2025-10-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminel', '0002_criminalfichecriminelle_antecedent_judiciaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminalfichecriminelle',
            name='cin',
            field=models.CharField(blank=True, help_text='Format: XXX XXX XXX XXX (12 chiffres)', max_length=15, null=True, verbose_name="CIN (Carte d'Identité Nationale)"),
        ),
        migrations.AlterField(
            model_name='criminalfichecriminelle',
            name='prenom',
            field=models.CharField(default='', max_length=100, verbose_name='Prénom'),
        ),
    ]
