# Generated by Django 4.2.7 on 2025-10-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminel', '0003_alter_criminalfichecriminelle_cin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminalfichecriminelle',
            name='prenom',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
    ]
