# Generated by Django 4.2.7 on 2025-10-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminel', '0004_alter_criminalfichecriminelle_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='niveau_danger',
            field=models.IntegerField(choices=[(1, 'Faible'), (2, 'Modéré'), (3, 'Élevé'), (4, 'Très Élevé'), (5, 'Extrême')], default=2, help_text='Évaluation du niveau de dangerosité (1=Faible, 5=Extrême)', verbose_name='Niveau de danger'),
        ),
    ]
