# Generated by Django 4.2.7 on 2025-10-24 20:05

import criminel.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('criminel', '0005_criminalfichecriminelle_niveau_danger'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='date_enregistrement',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Date d'enregistrement"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='criminalfichecriminelle',
            name='photo',
            field=models.ImageField(blank=True, help_text='La photo sera automatiquement nommée avec le numéro de fiche et le nom du criminel', null=True, upload_to=criminel.models.upload_photo_criminel, verbose_name='Photo'),
        ),
    ]
