# Generated by Django 4.2.7 on 2025-10-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminel', '0007_add_embedding_facial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminalfichecriminelle',
            name='embedding_facial',
        ),
    ]
