# Generated by Django 4.2.7 on 2025-10-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminel', '0008_remove_criminalfichecriminelle_embedding_facial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
