# Generated by Django 4.2.7 on 2025-11-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminel', '0009_criminalfichecriminelle_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='province',
            field=models.CharField(blank=True, help_text="Province/Region d'arrestation", max_length=100, null=True, verbose_name='Province'),
        ),
    ]
