# Generated by Django 4.2.7 on 2025-11-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminel', '0010_add_province_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Indique si la fiche est archivée', verbose_name='Archivée'),
        ),
    ]
