# Generated by Django 4.2.7 on 2025-11-11 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('criminel', '0011_add_is_archived_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Instructions')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('on_hold', 'Suspendue'), ('closed', 'Clôturée')], default='pending', max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(blank=True, help_text='Optionnel : faible, normale, élevée…', max_length=20, null=True, verbose_name='Priorité')),
                ('assignment_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'assignation")),
                ('due_date', models.DateField(blank=True, help_text='Date souhaitée de finalisation', null=True, verbose_name='Date cible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignations_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Assigné par')),
                ('assigned_investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignations_recuees', to=settings.AUTH_USER_MODEL, verbose_name='Enquêteur assigné')),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignations', to='criminel.criminalfichecriminelle', verbose_name='Dossier criminel')),
            ],
            options={
                'verbose_name': "Assignation d'enquête",
                'verbose_name_plural': "Assignations d'enquêtes",
                'db_table': 'investigation_assignment',
                'ordering': ('-assignment_date', '-id'),
                'indexes': [models.Index(fields=['status'], name='investigati_status_0996e0_idx'), models.Index(fields=['assigned_investigator', 'status'], name='investigati_assigne_cdcdb7_idx'), models.Index(fields=['fiche', 'assignment_date'], name='investigati_fiche_i_514af8_idx')],
            },
        ),
    ]
