# Generated by Django 4.2.7 on 2025-11-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminel', '0013_remove_email_interne_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigationassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('on_hold', 'Suspendue'), ('closed', 'Clôturée'), ('overdue', 'Échéance dépassée')], default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
