# Generated by Django 4.2.7 on 2025-11-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminel', '0015_criminalfichecriminelle_progression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigationassignment',
            name='due_date',
            field=models.DateField(blank=True, help_text="Date limite de finalisation de l'assignation (échéance)", null=True, verbose_name='Date limite'),
        ),
    ]
