# Generated by Django 4.2.7 on 2025-11-15 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('criminel', '0016_alter_investigationassignment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigationassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Assigné par'),
        ),
        migrations.AlterField(
            model_name='investigationassignment',
            name='assigned_investigator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Enquêteur assigné'),
        ),
    ]
