# Generated by Django 4.2.7 on 2025-11-26 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminel', '0018_add_biometric_fields_and_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminalfichecriminelle',
            name='email',
        ),
    ]
