# Generated by Django 4.2.7 on 2025-12-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminel', '0019_remove_email_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='district',
            field=models.CharField(blank=True, help_text="District d'arrestation (119 districts au total)", max_length=100, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='region',
            field=models.CharField(blank=True, help_text="Région d'arrestation (23 régions au total)", max_length=100, null=True, verbose_name='Région'),
        ),
        migrations.AlterField(
            model_name='criminalfichecriminelle',
            name='province',
            field=models.CharField(blank=True, help_text="Province historique d'arrestation", max_length=100, null=True, verbose_name='Province (Historique)'),
        ),
    ]
