# Generated by Django 4.2.7 on 2025-12-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminel', '0020_add_region_district_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='adresses_secondaires',
            field=models.TextField(blank=True, help_text='Autres adresses (domiciles secondaires, etc.)', null=True, verbose_name='Adresses secondaires'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='amis_proches',
            field=models.TextField(blank=True, help_text='Amis proches identifiés', null=True, verbose_name='Amis proches'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='anciennes_adresses',
            field=models.TextField(blank=True, help_text='Liste des anciennes adresses connues', null=True, verbose_name='Anciennes adresses'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='autres_reseaux',
            field=models.TextField(blank=True, help_text='Autres réseaux sociaux ou plateformes', null=True, verbose_name='Autres plateformes'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='biens_proprietes',
            field=models.TextField(blank=True, help_text='Biens immobiliers, véhicules, etc.', null=True, verbose_name='Biens ou propriétés'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='cartes_sim',
            field=models.TextField(blank=True, help_text='Cartes SIM identifiées', null=True, verbose_name='Cartes SIM'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='complices_potentiels',
            field=models.TextField(blank=True, help_text='Complices potentiels identifiés', null=True, verbose_name='Complices potentiels'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='comptes_bancaires',
            field=models.TextField(blank=True, help_text='Informations sur les comptes bancaires (si enquête autorisée)', null=True, verbose_name='Comptes bancaires'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='comptes_cloud',
            field=models.TextField(blank=True, help_text='Comptes cloud identifiés (iCloud, Google Drive, etc.)', null=True, verbose_name='Comptes cloud'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='consommation_alcool',
            field=models.BooleanField(default=False, verbose_name="Consommation d'alcool"),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='consommation_drogues',
            field=models.BooleanField(default=False, verbose_name='Consommation de drogues'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='contacts_recurrents',
            field=models.TextField(blank=True, help_text='Contacts récurrents identifiés', null=True, verbose_name='Contacts récurrents'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='dependants',
            field=models.TextField(blank=True, help_text='Personnes à charge', null=True, verbose_name='Dépendants'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='dettes_importantes',
            field=models.TextField(blank=True, help_text='Dettes connues ou significatives', null=True, verbose_name='Dettes importantes'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse e-mail'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='emplois_precedents',
            field=models.TextField(blank=True, help_text='Historique des emplois précédents', null=True, verbose_name='Emplois précédents'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='endroits_frequentes',
            field=models.TextField(blank=True, help_text='Bars, quartiers, villes fréquentés', null=True, verbose_name='Endroits fréquentés'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='entreprises_associees',
            field=models.TextField(blank=True, help_text='Entreprises où il/elle a travaillé ou est associé(e)', null=True, verbose_name='Entreprises associées'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='famille_proche',
            field=models.TextField(blank=True, help_text='Membres de la famille proche (parents, frères, sœurs)', null=True, verbose_name='Famille proche'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='frequentations_connues',
            field=models.TextField(blank=True, help_text='Personnes avec qui il/elle fréquente régulièrement', null=True, verbose_name='Fréquentations connues'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='geolocalisation_estimee',
            field=models.TextField(blank=True, help_text='Données de géolocalisation estimée', null=True, verbose_name='Géolocalisation estimée'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='historique_appels',
            field=models.TextField(blank=True, help_text="Historique d'appels (si légalement autorisé)", null=True, verbose_name="Historique d'appels"),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='imei',
            field=models.CharField(blank=True, help_text='Identifiant IMEI du téléphone', max_length=50, null=True, verbose_name='IMEI'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='imsi',
            field=models.CharField(blank=True, help_text='Identifiant IMSI de la carte SIM', max_length=50, null=True, verbose_name='IMSI'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='lieux_visites_frequemment',
            field=models.TextField(blank=True, help_text='Lieux régulièrement fréquentés', null=True, verbose_name='Lieux visités fréquemment'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='membres_reseau_criminel',
            field=models.TextField(blank=True, help_text="Membres identifiés d'un réseau criminel", null=True, verbose_name="Membres d'un réseau criminel"),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='messages_recuperes',
            field=models.TextField(blank=True, help_text='Messages récupérés (si autorisés légalement)', null=True, verbose_name='Messages récupérés'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='partenaire_affectif',
            field=models.CharField(blank=True, help_text='Partenaire affectif actuel', max_length=200, null=True, verbose_name='Partenaire affectif'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='permis_conduire',
            field=models.CharField(blank=True, help_text='Numéro de permis de conduire', max_length=50, null=True, verbose_name='Permis de conduire'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='personnes_proches',
            field=models.TextField(blank=True, help_text='Personnes proches importantes (famille, amis proches)', null=True, verbose_name='Personnes proches significatives'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='plaques_immatriculation',
            field=models.TextField(blank=True, help_text="Plaques d'immatriculation des véhicules", null=True, verbose_name="Plaques d'immatriculation"),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='sources_revenus',
            field=models.TextField(blank=True, help_text='Sources de revenus identifiées', null=True, verbose_name='Sources de revenus'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='statut_matrimonial',
            field=models.CharField(blank=True, choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf(ve)'), ('concubinage', 'En concubinage'), ('pacs', 'PACS')], max_length=50, null=True, verbose_name='Statut matrimonial'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='suspects_associes',
            field=models.TextField(blank=True, help_text='Autres suspects avec qui il/elle est associé(e)', null=True, verbose_name='Suspects associés'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='telephones_associes',
            field=models.TextField(blank=True, help_text='Numéros de téléphone et appareils associés', null=True, verbose_name='Téléphones associés'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='tiktok',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='trajets_habituels',
            field=models.TextField(blank=True, help_text='Itinéraires fréquemment empruntés', null=True, verbose_name='Trajets habituels'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='transactions_suspectes',
            field=models.TextField(blank=True, help_text='Transactions financières suspectes identifiées', null=True, verbose_name='Transactions suspectes'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='twitter_x',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='X (Twitter)'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='vehicules_associes',
            field=models.TextField(blank=True, help_text='Description des véhicules connus', null=True, verbose_name='Véhicules associés'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='WhatsApp (n° associé)'),
        ),
        migrations.AlterField(
            model_name='criminalfichecriminelle',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse actuelle'),
        ),
        migrations.AlterField(
            model_name='criminalfichecriminelle',
            name='distinguishing_marks',
            field=models.TextField(blank=True, help_text='Marques, cicatrices, particularités physiques, tatouages', null=True, verbose_name='Signes distinctifs'),
        ),
        migrations.AlterField(
            model_name='criminalfichecriminelle',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Emploi actuel'),
        ),
        migrations.AlterField(
            model_name='criminalfichecriminelle',
            name='spouse',
            field=models.CharField(blank=True, help_text='Nom du conjoint ou de la conjointe', max_length=200, null=True, verbose_name='Partenaire / Conjoint(e)'),
        ),
    ]
