# Generated by Django 4.2.7 on 2025-12-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminel', '0021_add_comprehensive_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='actions_futures_recommandees',
            field=models.TextField(blank=True, help_text='Actions recommandées pour les prochaines étapes', null=True, verbose_name='Actions futures recommandées'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='analyse_ia',
            field=models.TextField(blank=True, help_text="Résultats d'analyse par intelligence artificielle", null=True, verbose_name='Analyse IA'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='arrestations',
            field=models.TextField(blank=True, help_text='Historique des arrestations (dates, lieux, motifs)', null=True, verbose_name='Arrestations'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='audios_interrogatoire',
            field=models.TextField(blank=True, help_text="Références aux enregistrements audio d'interrogatoires", null=True, verbose_name="Audios d'interrogatoire"),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='condamnations',
            field=models.TextField(blank=True, help_text='Historique des condamnations (dates, peines, tribunaux)', null=True, verbose_name='Condamnations'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='documents_saisis',
            field=models.TextField(blank=True, help_text='Liste des documents saisis', null=True, verbose_name='Documents saisis'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='indicateurs_comportementaux',
            field=models.TextField(blank=True, help_text='Indicateurs comportementaux observés ou documentés', null=True, verbose_name='Indicateurs comportementaux'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='langues_parlees',
            field=models.TextField(blank=True, help_text="Langues que l'individu parle couramment", null=True, verbose_name='Langues parlées'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='liberte_conditionnelle',
            field=models.TextField(blank=True, help_text='Informations sur la liberté conditionnelle', null=True, verbose_name='Liberté conditionnelle'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='mandats_actifs',
            field=models.TextField(blank=True, help_text="Mandats d'arrêt actifs", null=True, verbose_name='Mandats actifs'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='mandats_expires',
            field=models.TextField(blank=True, help_text='Historique des mandats expirés', null=True, verbose_name='Mandats expirés'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='menace_potentielle',
            field=models.TextField(blank=True, help_text='Évaluation de la menace potentielle', null=True, verbose_name='Menace potentielle'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='mode_operatoire',
            field=models.TextField(blank=True, help_text='Description du mode opératoire caractéristique', null=True, verbose_name='Mode opératoire'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='motivation_probable',
            field=models.TextField(blank=True, help_text='Motivations probables identifiées', null=True, verbose_name='Motivation probable'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='niveau_risque_global',
            field=models.IntegerField(blank=True, choices=[(1, 'Minimal'), (2, 'Faible'), (3, 'Modéré'), (4, 'Élevé'), (5, 'Critique')], help_text='Évaluation globale du niveau de risque', null=True, verbose_name='Niveau de risque global'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='numero_identification_criminel',
            field=models.CharField(blank=True, help_text='Identifiant unique dans le système SGIC', max_length=100, null=True, verbose_name="Numéro d'identification criminel (ID SGIC)"),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='numero_judiciaire',
            field=models.CharField(blank=True, help_text='Numéro de référence judiciaire si lié à une affaire spécifique', max_length=100, null=True, verbose_name='Numéro judiciaire (si affaire)'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='numero_passeport',
            field=models.CharField(blank=True, help_text='Numéro de passeport (si autorisé et disponible)', max_length=50, null=True, verbose_name='Numéro de passeport'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='periodes_incarceration',
            field=models.TextField(blank=True, help_text="Historique des périodes d'incarcération", null=True, verbose_name="Périodes d'incarcération"),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='photos_preuves',
            field=models.TextField(blank=True, help_text='Références aux photos de preuves stockées', null=True, verbose_name='Photos des preuves'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='profil_psychologique',
            field=models.TextField(blank=True, help_text="Analyse psychologique de l'individu", null=True, verbose_name='Profil psychologique'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='pseudonymes_connus',
            field=models.TextField(blank=True, help_text='Tous les surnoms, alias et pseudonymes connus (un par ligne)', null=True, verbose_name='Surnoms / alias / pseudonymes connus'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='rapport_medicolegal',
            field=models.TextField(blank=True, help_text='Rapport médico-légal si applicable', null=True, verbose_name='Rapport médico-légal'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='rapports_scientifiques',
            field=models.TextField(blank=True, help_text="Rapports du technicien d'investigation", null=True, verbose_name='Rapports scientifiques (TI)'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='recommandation_surveillance',
            field=models.TextField(blank=True, help_text='Recommandations spécifiques pour la surveillance', null=True, verbose_name='Recommandation de surveillance'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='relations_risque',
            field=models.TextField(blank=True, help_text='Relations identifiées comme potentiellement à risque', null=True, verbose_name='Relations à risque'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='resume_individu',
            field=models.TextField(blank=True, help_text="Synthèse complète de l'individu", null=True, verbose_name="Résumé de l'individu"),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='risque_recidive',
            field=models.IntegerField(blank=True, choices=[(1, 'Très faible'), (2, 'Faible'), (3, 'Modéré'), (4, 'Élevé'), (5, 'Très élevé')], help_text='Évaluation du risque de récidive', null=True, verbose_name='Risque de récidive'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='signature_criminelle',
            field=models.TextField(blank=True, help_text='Signature ou caractéristiques distinctives des crimes commis', null=True, verbose_name='Signature criminelle'),
        ),
        migrations.AddField(
            model_name='criminalfichecriminelle',
            name='videos_preuves',
            field=models.TextField(blank=True, help_text='Références aux vidéos de preuves stockées', null=True, verbose_name='Vidéos'),
        ),
        migrations.AddField(
            model_name='criminalinfraction',
            name='description_detaillee',
            field=models.TextField(blank=True, help_text="Description complète et détaillée de l'infraction", null=True, verbose_name='Description détaillée'),
        ),
        migrations.AddField(
            model_name='criminalinfraction',
            name='enqueteur_responsable',
            field=models.CharField(blank=True, help_text="Nom et fonction de l'enquêteur responsable", max_length=200, null=True, verbose_name='Enquêteur responsable'),
        ),
        migrations.AddField(
            model_name='criminalinfraction',
            name='numero_affaire',
            field=models.CharField(blank=True, help_text="Numéro de référence de l'affaire judiciaire", max_length=100, null=True, verbose_name="Numéro d'affaire"),
        ),
        migrations.AddField(
            model_name='criminalinfraction',
            name='preuves_associees',
            field=models.TextField(blank=True, help_text='Liste des preuves associées à cette infraction', null=True, verbose_name='Preuves associées'),
        ),
        migrations.AddField(
            model_name='criminalinfraction',
            name='statut_affaire_texte',
            field=models.CharField(blank=True, help_text='En cours / Clôturée / Classée', max_length=50, null=True, verbose_name="Statut de l'affaire"),
        ),
    ]
