# Generated by Django 4.2.7 on 2025-12-06 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criminel', '0023_add_cursor_pagination_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminalinfraction',
            name='statut_affaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infractions_par_statut', to='criminel.refstatutaffaire'),
        ),
        migrations.AlterField(
            model_name='criminalinfraction',
            name='type_infraction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infractions_par_type', to='criminel.criminaltypeinfraction'),
        ),
    ]
