# Generated by Django 4.2.7 on 2026-03-19 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('criminel', '0024_alter_criminalinfraction_statut_affaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminalfichecriminelle',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('brun', 'Brun'), ('noir', 'Noir'), ('bleu', 'Bleu'), ('vert', 'Vert'), ('gris', 'Gris'), ('noisette', 'Noisette'), ('ambre', 'Ambre')], max_length=50, null=True, verbose_name='Couleur des yeux'),
        ),
        migrations.AlterField(
            model_name='investigationassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignations_creees', to=settings.AUTH_USER_MODEL, verbose_name='Assigné par'),
        ),
        migrations.AlterField(
            model_name='investigationassignment',
            name='assigned_investigator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignations_recues', to=settings.AUTH_USER_MODEL, verbose_name='Enquêteur assigné'),
        ),
        migrations.AlterField(
            model_name='investigationassignment',
            name='priority',
            field=models.CharField(choices=[('faible', 'Faible'), ('normale', 'Normale'), ('elevee', 'Élevée'), ('urgente', 'Urgente')], default='normale', max_length=20, verbose_name='Priorité'),
        ),
        migrations.AddIndex(
            model_name='criminalfichecriminelle',
            index=models.Index(fields=['is_archived'], name='criminal_fi_is_arch_2a6e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='criminalfichecriminelle',
            index=models.Index(fields=['statut_fiche'], name='criminal_fi_statut__b5bb28_idx'),
        ),
        migrations.AddIndex(
            model_name='criminalfichecriminelle',
            index=models.Index(fields=['niveau_danger'], name='criminal_fi_niveau__8ff7f2_idx'),
        ),
        migrations.AddIndex(
            model_name='investigationassignment',
            index=models.Index(fields=['due_date'], name='investigati_due_dat_354b6a_idx'),
        ),
    ]
