# Generated by Django 4.2.7 on 2025-10-22 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('criminel', '0004_alter_criminalfichecriminelle_prenom'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometriePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='biometrie/photos/')),
                ('type_photo', models.CharField(choices=[('face', 'Face'), ('profil_gauche', 'Profil gauche'), ('profil_droit', 'Profil droit')], max_length=50, verbose_name='Type de photo')),
                ('date_capture', models.DateTimeField(auto_now_add=True, verbose_name='Date de capture')),
                ('capture_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Capturee par')),
                ('criminel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_biometriques', to='criminel.criminalfichecriminelle')),
            ],
            options={
                'verbose_name': 'Photo biometrique',
                'verbose_name_plural': 'Photos biometriques',
                'db_table': 'biometrie_photo',
                'ordering': ['-date_capture'],
            },
        ),
        migrations.CreateModel(
            name='BiometrieEmpreinte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='biometrie/empreintes/')),
                ('doigt', models.CharField(choices=[('pouce_droit', 'Pouce droit'), ('index_droit', 'Index droit'), ('majeur_droit', 'Majeur droit'), ('annulaire_droit', 'Annulaire droit'), ('auriculaire_droit', 'Auriculaire droit'), ('pouce_gauche', 'Pouce gauche'), ('index_gauche', 'Index gauche'), ('majeur_gauche', 'Majeur gauche'), ('annulaire_gauche', 'Annulaire gauche'), ('auriculaire_gauche', 'Auriculaire gauche')], max_length=50, verbose_name='Doigt')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name='Date enregistrement')),
                ('criminel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empreintes_digitales', to='criminel.criminalfichecriminelle')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enregistree par')),
            ],
            options={
                'verbose_name': 'Empreinte digitale',
                'verbose_name_plural': 'Empreintes digitales',
                'db_table': 'biometrie_empreinte',
                'ordering': ['-date_enregistrement'],
            },
        ),
    ]
