# Generated by Django 4.2.7 on 2025-10-23 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('criminel', '0004_alter_criminalfichecriminelle_prenom'),
        ('biometrie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometrieScanResultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_scan', models.CharField(choices=[('facial', 'Reconnaissance faciale'), ('empreinte', "Reconnaissance d'empreinte")], max_length=50, verbose_name='Type de scan')),
                ('image_source', models.ImageField(help_text='Image utilisée pour la recherche', upload_to='biometrie/scans/', verbose_name='Image source')),
                ('score_correspondance', models.FloatField(default=0.0, help_text='Score de similarité (0.0 à 1.0)', verbose_name='Score de correspondance')),
                ('seuil_confiance', models.FloatField(default=0.75, help_text='Seuil minimal pour considérer une correspondance valide', verbose_name='Seuil de confiance')),
                ('resultats_json', models.TextField(blank=True, help_text='Détails complets des résultats de scan (format JSON)', null=True, verbose_name='Résultats détaillés')),
                ('nombre_comparaisons', models.IntegerField(default=0, verbose_name='Nombre de comparaisons effectuées')),
                ('temps_execution', models.FloatField(default=0.0, verbose_name="Temps d'exécution (secondes)")),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('echec', 'Échec')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('date_scan', models.DateTimeField(auto_now_add=True, verbose_name='Date du scan')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Résultat de scan biométrique',
                'verbose_name_plural': 'Résultats de scans biométriques',
                'db_table': 'biometrie_scan_resultat',
                'ordering': ['-date_scan'],
            },
        ),
        migrations.AlterModelOptions(
            name='biometriephoto',
            options={'ordering': ['-date_capture'], 'verbose_name': 'Photo biométrique', 'verbose_name_plural': 'Photos biométriques'},
        ),
        migrations.AddField(
            model_name='biometrieempreinte',
            name='encodage_empreinte',
            field=models.TextField(blank=True, help_text='Encodage biométrique pour la reconnaissance (format JSON)', null=True, verbose_name="Encodage de l'empreinte"),
        ),
        migrations.AddField(
            model_name='biometrieempreinte',
            name='est_active',
            field=models.BooleanField(default=True, help_text='Indique si cette empreinte est utilisable pour la reconnaissance', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='biometrieempreinte',
            name='minuties',
            field=models.TextField(blank=True, help_text="Points caractéristiques de l'empreinte (format JSON)", null=True, verbose_name='Minuties'),
        ),
        migrations.AddField(
            model_name='biometrieempreinte',
            name='nombre_minuties',
            field=models.IntegerField(default=0, verbose_name='Nombre de minuties détectées'),
        ),
        migrations.AddField(
            model_name='biometrieempreinte',
            name='notes',
            field=models.TextField(blank=True, help_text="Observations sur l'empreinte", null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='biometrieempreinte',
            name='qualite',
            field=models.IntegerField(default=0, help_text='Score de qualité de 0 à 100', verbose_name="Qualité de l'empreinte"),
        ),
        migrations.AddField(
            model_name='biometrieempreinte',
            name='taille_fichier',
            field=models.IntegerField(blank=True, null=True, verbose_name='Taille du fichier (bytes)'),
        ),
        migrations.AddField(
            model_name='biometrieempreinte',
            name='type_empreinte',
            field=models.CharField(blank=True, choices=[('arche', 'Arche'), ('boucle', 'Boucle'), ('verticille', 'Verticille'), ('composite', 'Composite')], help_text='Classification dactyloscopique', max_length=50, null=True, verbose_name="Type d'empreinte"),
        ),
        migrations.AddField(
            model_name='biometriephoto',
            name='encodage_facial',
            field=models.TextField(blank=True, help_text='Encodage biométrique pour la reconnaissance faciale (format JSON)', null=True, verbose_name='Encodage facial'),
        ),
        migrations.AddField(
            model_name='biometriephoto',
            name='est_active',
            field=models.BooleanField(default=True, help_text='Indique si cette photo est utilisable pour la reconnaissance faciale', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='biometriephoto',
            name='est_principale',
            field=models.BooleanField(default=False, help_text='Indique si cette photo est la photo principale du dossier', verbose_name='Photo principale'),
        ),
        migrations.AddField(
            model_name='biometriephoto',
            name='notes',
            field=models.TextField(blank=True, help_text='Observations sur la photo', null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='biometriephoto',
            name='qualite',
            field=models.IntegerField(default=0, help_text='Score de qualité de 0 à 100', verbose_name="Qualité de l'image"),
        ),
        migrations.AddField(
            model_name='biometriephoto',
            name='taille_fichier',
            field=models.IntegerField(blank=True, null=True, verbose_name='Taille du fichier (bytes)'),
        ),
        migrations.AlterField(
            model_name='biometrieempreinte',
            name='criminel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empreintes_digitales', to='criminel.criminalfichecriminelle', verbose_name='Criminel'),
        ),
        migrations.AlterField(
            model_name='biometrieempreinte',
            name='date_enregistrement',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement"),
        ),
        migrations.AlterField(
            model_name='biometrieempreinte',
            name='enregistre_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empreintes_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name='Enregistrée par'),
        ),
        migrations.AlterField(
            model_name='biometrieempreinte',
            name='image',
            field=models.ImageField(upload_to='biometrie/empreintes/', verbose_name="Image de l'empreinte"),
        ),
        migrations.AlterField(
            model_name='biometriephoto',
            name='capture_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos_capturees', to=settings.AUTH_USER_MODEL, verbose_name='Capturée par'),
        ),
        migrations.AlterField(
            model_name='biometriephoto',
            name='criminel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_biometriques', to='criminel.criminalfichecriminelle', verbose_name='Criminel'),
        ),
        migrations.AlterField(
            model_name='biometriephoto',
            name='image',
            field=models.ImageField(help_text='Photo biométrique du criminel', upload_to='biometrie/photos/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='biometriephoto',
            name='type_photo',
            field=models.CharField(choices=[('face', 'Face'), ('profil_gauche', 'Profil gauche'), ('profil_droit', 'Profil droit'), ('face_3_4', 'Face 3/4')], max_length=50, verbose_name='Type de photo'),
        ),
        migrations.AlterUniqueTogether(
            name='biometrieempreinte',
            unique_together={('criminel', 'doigt')},
        ),
        migrations.AddIndex(
            model_name='biometrieempreinte',
            index=models.Index(fields=['criminel', 'doigt'], name='biometrie_e_crimine_4deff5_idx'),
        ),
        migrations.AddIndex(
            model_name='biometrieempreinte',
            index=models.Index(fields=['type_empreinte'], name='biometrie_e_type_em_e1d474_idx'),
        ),
        migrations.AddIndex(
            model_name='biometrieempreinte',
            index=models.Index(fields=['-date_enregistrement'], name='biometrie_e_date_en_1c3855_idx'),
        ),
        migrations.AddIndex(
            model_name='biometriephoto',
            index=models.Index(fields=['criminel', '-date_capture'], name='biometrie_p_crimine_ca967c_idx'),
        ),
        migrations.AddIndex(
            model_name='biometriephoto',
            index=models.Index(fields=['type_photo'], name='biometrie_p_type_ph_f430cf_idx'),
        ),
        migrations.AddIndex(
            model_name='biometriephoto',
            index=models.Index(fields=['est_principale'], name='biometrie_p_est_pri_24f4f0_idx'),
        ),
        migrations.AddField(
            model_name='biometriescanresultat',
            name='criminel_correspondant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultats_scans', to='criminel.criminalfichecriminelle', verbose_name='Criminel correspondant'),
        ),
        migrations.AddField(
            model_name='biometriescanresultat',
            name='execute_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans_executes', to=settings.AUTH_USER_MODEL, verbose_name='Exécuté par'),
        ),
        migrations.AddIndex(
            model_name='biometriescanresultat',
            index=models.Index(fields=['-date_scan'], name='biometrie_s_date_sc_9bbfa3_idx'),
        ),
        migrations.AddIndex(
            model_name='biometriescanresultat',
            index=models.Index(fields=['type_scan', 'statut'], name='biometrie_s_type_sc_c17f21_idx'),
        ),
        migrations.AddIndex(
            model_name='biometriescanresultat',
            index=models.Index(fields=['criminel_correspondant'], name='biometrie_s_crimine_69c3db_idx'),
        ),
    ]
