# Generated by Django 4.2.7 on 2025-10-24 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criminel', '0005_criminalfichecriminelle_niveau_danger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biometrie', '0002_biometriescanresultat_alter_biometriephoto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometriePaume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='biometrie/paumes/', verbose_name="Image de l'empreinte palmaire")),
                ('paume', models.CharField(choices=[('paume_droite', 'Paume droite'), ('paume_gauche', 'Paume gauche')], max_length=50, verbose_name='Paume')),
                ('qualite', models.IntegerField(default=0, help_text='Score de qualité de 0 à 10', verbose_name="Qualité de l'empreinte")),
                ('resolution', models.CharField(blank=True, help_text='Ex: 1500x2000px', max_length=50, null=True, verbose_name='Résolution')),
                ('taille_fichier', models.IntegerField(blank=True, null=True, verbose_name='Taille du fichier (bytes)')),
                ('notes', models.TextField(blank=True, help_text="Observations sur l'empreinte palmaire", null=True, verbose_name='Notes')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('est_active', models.BooleanField(default=True, help_text='Indique si cette empreinte est utilisable pour la reconnaissance', verbose_name='Active')),
                ('criminel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empreintes_palmaires', to='criminel.criminalfichecriminelle', verbose_name='Criminel')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paumes_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name='Enregistrée par')),
            ],
            options={
                'verbose_name': 'Empreinte palmaire',
                'verbose_name_plural': 'Empreintes palmaires',
                'db_table': 'biometrie_paume',
                'ordering': ['-date_enregistrement'],
                'indexes': [models.Index(fields=['criminel', 'paume'], name='biometrie_p_crimine_51874c_idx'), models.Index(fields=['-date_enregistrement'], name='biometrie_p_date_en_647612_idx')],
                'unique_together': {('criminel', 'paume')},
            },
        ),
    ]
