# Generated by Django 4.2.7 on 2025-10-25 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criminel', '0006_criminalfichecriminelle_date_enregistrement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biometrie', '0004_add_legal_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometrieempreinte',
            name='base_legale',
        ),
        migrations.RemoveField(
            model_name='biometrieempreinte',
            name='date_expiration',
        ),
        migrations.RemoveField(
            model_name='biometrieempreinte',
            name='numero_procedure',
        ),
        migrations.RemoveField(
            model_name='biometrieempreinte',
            name='statut_legal',
        ),
        migrations.RemoveField(
            model_name='biometriephoto',
            name='base_legale',
        ),
        migrations.RemoveField(
            model_name='biometriephoto',
            name='consentement_obtenu',
        ),
        migrations.RemoveField(
            model_name='biometriephoto',
            name='date_consentement',
        ),
        migrations.RemoveField(
            model_name='biometriephoto',
            name='date_expiration',
        ),
        migrations.RemoveField(
            model_name='biometriephoto',
            name='finalite_traitement',
        ),
        migrations.RemoveField(
            model_name='biometriephoto',
            name='numero_procedure',
        ),
        migrations.RemoveField(
            model_name='biometriephoto',
            name='statut_legal',
        ),
        migrations.RemoveField(
            model_name='biometriescanresultat',
            name='justification_recherche',
        ),
        migrations.RemoveField(
            model_name='biometriescanresultat',
            name='validation_hierarchique',
        ),
        migrations.CreateModel(
            name='BiometrieHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_objet', models.CharField(choices=[('photo', 'Photo biométrique'), ('empreinte', 'Empreinte digitale'), ('paume', 'Empreinte palmaire'), ('scan', 'Résultat de scan')], max_length=50, verbose_name="Type d'objet")),
                ('objet_id', models.IntegerField(help_text="ID de l'objet modifié", verbose_name="ID de l'objet")),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('activation', 'Activation'), ('desactivation', 'Désactivation'), ('encodage', 'Génération encodage'), ('principale', 'Définie comme principale')], max_length=50, verbose_name='Action effectuée')),
                ('description', models.TextField(blank=True, help_text="Détails de l'action effectuée", null=True, verbose_name='Description')),
                ('donnees_avant', models.JSONField(blank=True, help_text='État des données avant la modification (format JSON)', null=True, verbose_name='Données avant modification')),
                ('donnees_apres', models.JSONField(blank=True, help_text='État des données après la modification (format JSON)', null=True, verbose_name='Données après modification')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('adresse_ip', models.GenericIPAddressField(blank=True, help_text="Adresse IP de l'utilisateur", null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, help_text='Navigateur/client utilisé', null=True, verbose_name='User Agent')),
                ('criminel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_biometrie', to='criminel.criminalfichecriminelle', verbose_name='Criminel concerné')),
                ('effectue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_biometrie', to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
            ],
            options={
                'verbose_name': 'Historique biométrique',
                'verbose_name_plural': 'Historiques biométriques',
                'db_table': 'biometrie_historique',
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['type_objet', 'objet_id'], name='biometrie_h_type_ob_645d2a_idx'), models.Index(fields=['criminel', '-date_action'], name='biometrie_h_crimine_17b539_idx'), models.Index(fields=['action', '-date_action'], name='biometrie_h_action_03ba19_idx'), models.Index(fields=['effectue_par', '-date_action'], name='biometrie_h_effectu_28786f_idx')],
            },
        ),
    ]
