# Generated by Django 4.2.7 on 2025-11-02 17:46

import biometrie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrie', '0005_remove_biometrieempreinte_base_legale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometrieempreinte',
            name='image',
            field=models.ImageField(upload_to='biometrie/empreintes/', validators=[biometrie.models.validate_image_file], verbose_name="Image de l'empreinte"),
        ),
        migrations.AlterField(
            model_name='biometriepaume',
            name='image',
            field=models.ImageField(upload_to='biometrie/paumes/', validators=[biometrie.models.validate_image_file], verbose_name="Image de l'empreinte palmaire"),
        ),
        migrations.AlterField(
            model_name='biometriephoto',
            name='image',
            field=models.ImageField(help_text='Photo biométrique du criminel (JPG, PNG uniquement, max 10MB)', upload_to='biometrie/photos/', validators=[biometrie.models.validate_image_file], verbose_name='Image'),
        ),
    ]
