# Generated by Django 4.2.7 on 2025-11-07 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biometrie', '0007_biometrie'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='biometrie',
            new_name='biometrie_e_crimine_45864e_idx',
            old_name='biometrie_e_crimine_a8960f_idx',
        ),
    ]
