# Generated by Django 4.2.7 on 2025-11-15 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biometrie', '0008_rename_biometrie_e_crimine_a8960f_idx_biometrie_e_crimine_45864e_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometrieempreinte',
            name='enregistre_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Enregistrée par'),
        ),
        migrations.AlterField(
            model_name='biometriehistorique',
            name='effectue_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Effectué par'),
        ),
        migrations.AlterField(
            model_name='biometriepaume',
            name='enregistre_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Enregistrée par'),
        ),
        migrations.AlterField(
            model_name='biometriephoto',
            name='capture_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Capturée par'),
        ),
        migrations.AlterField(
            model_name='biometriescanresultat',
            name='execute_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Exécuté par'),
        ),
    ]
