# Generated by Django 4.2.7 on 2025-11-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrie', '0009_alter_biometrieempreinte_enregistre_par_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometriephoto',
            name='embedding_512',
            field=models.JSONField(blank=True, help_text="Vecteur d'embedding ArcFace de 512 dimensions (format JSON array)", null=True, verbose_name='Embedding ArcFace 512-d'),
        ),
        migrations.AddField(
            model_name='biometriephoto',
            name='facemesh_468',
            field=models.JSONField(blank=True, help_text='468 points 3D FaceMesh [[x, y, z], ...] (format JSON array)', null=True, verbose_name='FaceMesh 468 points 3D'),
        ),
        migrations.AddField(
            model_name='biometriephoto',
            name='landmarks_106',
            field=models.JSONField(blank=True, help_text='106 points de repère faciaux [[x, y], ...] (format JSON array)', null=True, verbose_name='Landmarks 106 points'),
        ),
        migrations.AddField(
            model_name='biometriephoto',
            name='morphable_3d',
            field=models.JSONField(blank=True, help_text='Paramètres du modèle 3D Morphable (vertices, shape_params, etc.)', null=True, verbose_name='Modèle 3D Morphable'),
        ),
    ]
