# Generated by Django 4.2.7 on 2025-12-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrie', '0010_biometriephoto_embedding_512_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometriephoto',
            name='type_photo',
            field=models.CharField(choices=[('face', 'Face'), ('profil_gauche', 'Profil gauche'), ('profil_droit', 'Profil droit'), ('face_3_4', 'Face 3/4'), ('plein_pied', 'Photo plein pied'), ('contextuelle', 'Photo contextuelle'), ('tatouage', 'Photo de tatouage'), ('cicatrice', 'Photo de cicatrice'), ('marque', 'Photo de marque particulière')], max_length=50, verbose_name='Type de photo'),
        ),
    ]
