# Generated by Django 4.2.7 on 2025-12-06 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrie', '0011_add_photo_types_plein_pied_contextuelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometriephoto',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True, help_text='Date de dernière mise à jour (embedding, landmarks, etc.)', verbose_name='Dernière mise à jour'),
        ),
        migrations.AddField(
            model_name='biometriephoto',
            name='niveau_confiance',
            field=models.FloatField(blank=True, help_text="Niveau de confiance de l'embedding ArcFace (0.0 à 1.0)", null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Niveau de confiance'),
        ),
    ]
