# Generated by Django 4.2.7 on 2026-06-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrie', '0012_biometriephoto_date_mise_a_jour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometriehistorique',
            name='type_objet',
            field=models.CharField(choices=[('photo', 'Photo biométrique'), ('empreinte', 'Empreinte digitale'), ('paume', 'Empreinte palmaire'), ('scan', 'Résultat de scan'), ('encodage', 'Encodage facial (Biometrie)')], max_length=50, verbose_name="Type d'objet"),
        ),
    ]
