# Generated by Django 4.2.7 on 2025-11-07 21:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnes',
                'db_table': 'face_recognition_person',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='face_recogn_name_3252ac_idx'), models.Index(fields=['email'], name='face_recogn_email_42c91b_idx'), models.Index(fields=['-created_at'], name='face_recogn_created_754c71_idx')],
            },
        ),
        migrations.CreateModel(
            name='FaceRecognitionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding_vector', models.JSONField(help_text="Embedding extrait de l'image de reconnaissance", verbose_name="Vecteur d'embedding")),
                ('confidence_score', models.FloatField(help_text='Score de confiance de la reconnaissance (0.0 à 1.0)', verbose_name='Score de confiance')),
                ('image_path', models.CharField(help_text="Chemin vers l'image utilisée pour la reconnaissance", max_length=500, verbose_name="Chemin de l'image")),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Horodatage')),
                ('status', models.CharField(choices=[('recognized', 'Reconnu'), ('unknown', 'Inconnu')], help_text='Statut de la reconnaissance', max_length=20, verbose_name='Statut')),
                ('threshold_used', models.FloatField(default=0.6, help_text='Seuil de confiance utilisé pour cette reconnaissance', verbose_name='Seuil utilisé')),
                ('processing_time_ms', models.FloatField(blank=True, help_text='Temps de traitement en millisecondes', null=True, verbose_name='Temps de traitement (ms)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_recognition_logs', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('detected_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_logs', to='face_recognition.person', verbose_name='Personne détectée')),
            ],
            options={
                'verbose_name': 'Log de reconnaissance',
                'verbose_name_plural': 'Logs de reconnaissance',
                'db_table': 'face_recognition_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['detected_person'], name='face_recogn_detecte_476a13_idx'), models.Index(fields=['status'], name='face_recogn_status_132e83_idx'), models.Index(fields=['timestamp'], name='face_recogn_timesta_e2a183_idx'), models.Index(fields=['confidence_score'], name='face_recogn_confide_be6d7c_idx')],
            },
        ),
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding', models.JSONField(help_text="Vecteur d'embedding ArcFace (512 dimensions) au format JSON", verbose_name='Embedding facial')),
                ('image_path', models.CharField(help_text='Chemin vers le fichier image stocké', max_length=500, verbose_name="Chemin de l'image")),
                ('confidence_score', models.FloatField(default=0.0, help_text="Score de confiance de l'extraction (0.0 à 1.0)", verbose_name='Score de confiance')),
                ('image_width', models.IntegerField(blank=True, null=True, verbose_name="Largeur de l'image")),
                ('image_height', models.IntegerField(blank=True, null=True, verbose_name="Hauteur de l'image")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to='face_recognition.person', verbose_name='Personne')),
            ],
            options={
                'verbose_name': 'Embedding facial',
                'verbose_name_plural': 'Embeddings faciaux',
                'db_table': 'face_recognition_face_embedding',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['person'], name='face_recogn_person__9fb744_idx'), models.Index(fields=['confidence_score'], name='face_recogn_confide_38a6a0_idx'), models.Index(fields=['-created_at'], name='face_recogn_created_3d84c3_idx')],
            },
        ),
    ]
