# Generated by Django 4.2.7 on 2025-11-26 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition', '0002_alter_facerecognitionlog_created_by'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='person',
            name='face_recogn_email_42c91b_idx',
        ),
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
    ]
