# Generated by Django 4.2.7 on 2025-10-30 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_utilisa_1ca1e0_idx',
            old_name='Notificatio_utilisa_20e8d9_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_utilisa_74632e_idx',
            old_name='Notificatio_utilisa_493dfa_idx',
        ),
    ]
