# Generated by Django 4.2.7 on 2025-11-12 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('consultation', 'Consultation'), ('connexion', 'Connexion'), ('deconnexion', 'Déconnexion'), ('export', 'Export'), ('import', 'Import'), ('validation', 'Validation'), ('rejet', 'Rejet'), ('telechargement', 'Téléchargement'), ('upload', 'Upload'), ('recherche', 'Recherche'), ('autre', 'Autre')], max_length=50, verbose_name='Action')),
                ('ressource', models.CharField(help_text='Type de ressource concernée (ex: Fiche Criminelle, Utilisateur, etc.)', max_length=255, verbose_name='Ressource')),
                ('ressource_id', models.CharField(blank=True, help_text='Identifiant de la ressource concernée', max_length=100, null=True, verbose_name='ID de la ressource')),
                ('description', models.TextField(blank=True, help_text="Description intelligente générée automatiquement par l'IA", null=True, verbose_name='Description')),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, help_text="Navigateur et système d'exploitation de l'utilisateur", null=True, verbose_name='User Agent')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Informations complémentaires au format JSON', verbose_name='Détails supplémentaires')),
                ('date_action', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Date de l'action")),
                ('reussi', models.BooleanField(default=True, help_text="Indique si l'action a été effectuée avec succès", verbose_name='Action réussie')),
                ('message_erreur', models.TextField(blank=True, help_text="Message d'erreur si l'action a échoué", null=True, verbose_name="Message d'erreur")),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_audit', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Entrée du Journal d'Audit",
                'verbose_name_plural': "Journal d'Audit",
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['-date_action'], name='audit_journ_date_ac_8b197b_idx'), models.Index(fields=['utilisateur', '-date_action'], name='audit_journ_utilisa_486ba0_idx'), models.Index(fields=['action', '-date_action'], name='audit_journ_action_82434c_idx'), models.Index(fields=['ressource', '-date_action'], name='audit_journ_ressour_53a8dd_idx')],
            },
        ),
    ]
