# Generated by Django 4.2.7 on 2025-11-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalaudit',
            name='duree_ms',
            field=models.IntegerField(blank=True, help_text='Durée de traitement en millisecondes', null=True, verbose_name='Durée (ms)'),
        ),
        migrations.AddField(
            model_name='journalaudit',
            name='endpoint',
            field=models.CharField(blank=True, help_text="URL/Endpoint de l'API appelée", max_length=500, null=True, verbose_name='Endpoint'),
        ),
        migrations.AddField(
            model_name='journalaudit',
            name='methode_http',
            field=models.CharField(blank=True, help_text='Méthode HTTP utilisée (GET, POST, PUT, DELETE, etc.)', max_length=10, null=True, verbose_name='Méthode HTTP'),
        ),
    ]
