# Generated by Django 4.2.7 on 2025-11-15 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0002_journalaudit_duree_ms_journalaudit_endpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalaudit',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
