# Generated by Django 4.2.7 on 2025-11-17 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0003_alter_journalaudit_utilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=50, verbose_name='Action')),
                ('resource', models.CharField(db_index=True, max_length=255, verbose_name='Ressource')),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de la ressource')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('endpoint', models.CharField(blank=True, max_length=500, null=True, verbose_name='Endpoint')),
                ('methode_http', models.CharField(blank=True, max_length=10, null=True, verbose_name='Méthode HTTP')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Détails')),
                ('date_action', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Date de l'action")),
                ('reussi', models.BooleanField(default=True, verbose_name='Action réussie')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Événement d'Audit",
                'verbose_name_plural': "Événements d'Audit",
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='AuditAIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrative_public', models.TextField(help_text='Phrase narrative claire pour non-informaticiens', verbose_name='Résumé narratif public')),
                ('narrative_admin', models.TextField(help_text='Résumé technique pour administrateurs', verbose_name='Résumé narratif admin')),
                ('confidence', models.IntegerField(default=0, help_text="Score de confiance de l'analyse (0-100)", verbose_name='Score de confiance')),
                ('risk_level', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('élevé', 'Élevé')], db_index=True, default='faible', max_length=10, verbose_name='Niveau de risque')),
                ('missing_fields', models.JSONField(blank=True, default=list, help_text="Liste des champs manquants qui auraient amélioré l'analyse", verbose_name='Champs manquants')),
                ('date_analyse', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Date d'analyse")),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_result', to='audit.auditevent', verbose_name="Événement d'audit")),
            ],
            options={
                'verbose_name': "Résultat d'Analyse IA",
                'verbose_name_plural': "Résultats d'Analyse IA",
                'ordering': ['-date_analyse'],
            },
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['-date_action'], name='audit_audit_date_ac_0d764c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['utilisateur', '-date_action'], name='audit_audit_utilisa_1e337c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['action', '-date_action'], name='audit_audit_action_049e61_idx'),
        ),
        migrations.AddIndex(
            model_name='auditairesult',
            index=models.Index(fields=['-date_analyse'], name='audit_audit_date_an_e0d705_idx'),
        ),
        migrations.AddIndex(
            model_name='auditairesult',
            index=models.Index(fields=['risk_level', '-date_analyse'], name='audit_audit_risk_le_07c37e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditairesult',
            index=models.Index(fields=['confidence', '-date_analyse'], name='audit_audit_confide_788fd0_idx'),
        ),
    ]
