# Generated by Django 4.2.7 on 2025-11-21 00:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auditevent_auditairesult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalaudit',
            name='device',
            field=models.CharField(blank=True, help_text="Informations sur l'appareil utilisé", max_length=255, null=True, verbose_name='Appareil'),
        ),
        migrations.AddField(
            model_name='journalaudit',
            name='method',
            field=models.CharField(blank=True, help_text='Méthode HTTP utilisée (GET, POST, PUT, DELETE, etc.)', max_length=10, null=True, verbose_name='Méthode HTTP'),
        ),
        migrations.AddField(
            model_name='journalaudit',
            name='page',
            field=models.CharField(blank=True, help_text='Page ou endpoint consulté', max_length=255, null=True, verbose_name='Page/Endpoint'),
        ),
        migrations.AddField(
            model_name='journalaudit',
            name='role',
            field=models.CharField(blank=True, help_text="Rôle de l'utilisateur au moment de l'action", max_length=100, null=True, verbose_name='Rôle'),
        ),
        migrations.AddField(
            model_name='journalaudit',
            name='target',
            field=models.CharField(blank=True, help_text="Cible de l'action (ex: FicheCriminelle#123)", max_length=255, null=True, verbose_name='Cible'),
        ),
        migrations.AddField(
            model_name='journalaudit',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='journalaudit',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'LOGIN'), ('LOGOUT', 'LOGOUT'), ('FAILED_LOGIN', 'FAILED_LOGIN'), ('VIEW', 'VIEW'), ('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE'), ('DOWNLOAD', 'DOWNLOAD'), ('SUSPEND', 'SUSPEND'), ('RESTORE', 'RESTORE'), ('PERMISSION_CHANGE', 'PERMISSION_CHANGE'), ('ACCESS_DENIED', 'ACCESS_DENIED'), ('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('consultation', 'Consultation'), ('connexion', 'Connexion'), ('deconnexion', 'Déconnexion'), ('export', 'Export'), ('import', 'Import'), ('validation', 'Validation'), ('rejet', 'Rejet'), ('telechargement', 'Téléchargement'), ('upload', 'Upload'), ('recherche', 'Recherche'), ('autre', 'Autre')], max_length=50, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='journalaudit',
            name='description',
            field=models.TextField(blank=True, help_text="Description de l'action (générée automatiquement)", null=True, verbose_name='Description'),
        ),
    ]
