# Generated by Django 4.2.7 on 2025-11-24 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0007_remove_audit_ai_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(blank=True, help_text="Rôle de l'utilisateur au moment de l'action", max_length=100, null=True, verbose_name='Rôle utilisateur')),
                ('action', models.CharField(choices=[('LOGIN', 'LOGIN'), ('LOGOUT', 'LOGOUT'), ('FAILED_LOGIN', 'FAILED_LOGIN'), ('VIEW', 'VIEW'), ('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE'), ('DOWNLOAD', 'DOWNLOAD'), ('SUSPEND', 'SUSPEND'), ('RESTORE', 'RESTORE'), ('PERMISSION_CHANGE', 'PERMISSION_CHANGE'), ('ACCESS_DENIED', 'ACCESS_DENIED')], db_index=True, max_length=50, verbose_name='Action')),
                ('resource_type', models.CharField(db_index=True, help_text='Type de ressource concernée (ex: Utilisateur, DossierCriminel, Preuve)', max_length=255, verbose_name='Type de ressource')),
                ('resource_id', models.CharField(blank=True, db_index=True, help_text='Identifiant de la ressource concernée', max_length=100, null=True, verbose_name='ID de la ressource')),
                ('endpoint', models.CharField(blank=True, db_index=True, help_text="URL/Endpoint de l'API appelée", max_length=500, null=True, verbose_name='Endpoint')),
                ('method', models.CharField(blank=True, help_text='Méthode HTTP utilisée (GET, POST, PUT, DELETE, etc.)', max_length=10, null=True, verbose_name='Méthode HTTP')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, help_text='User-Agent complet du navigateur', null=True, verbose_name='User Agent')),
                ('browser', models.CharField(blank=True, help_text='Nom et version du navigateur (ex: Google Chrome 142)', max_length=255, null=True, verbose_name='Navigateur')),
                ('os', models.CharField(blank=True, help_text="Système d'exploitation (ex: Windows 11, Linux Ubuntu)", max_length=255, null=True, verbose_name="Système d'exploitation")),
                ('data_before', models.JSONField(blank=True, default=dict, help_text='État de la ressource avant modification (format JSON)', verbose_name='Données avant')),
                ('data_after', models.JSONField(blank=True, default=dict, help_text='État de la ressource après modification (format JSON)', verbose_name='Données après')),
                ('description', models.TextField(blank=True, help_text="Description textuelle générée automatiquement pour l'interface", null=True, verbose_name='Description')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Timestamp')),
                ('reussi', models.BooleanField(default=True, help_text="Indique si l'action a été effectuée avec succès", verbose_name='Action réussie')),
                ('message_erreur', models.TextField(blank=True, help_text="Message d'erreur si l'action a échoué", null=True, verbose_name="Message d'erreur")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Entrée du Journal d'Audit",
                'verbose_name_plural': "Journal d'Audit",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='journalaudit',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='AuditEvent',
        ),
        migrations.DeleteModel(
            name='JournalAudit',
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='audit_audit_timesta_901180_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='audit_audit_user_id_ea8c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-timestamp'], name='audit_audit_action_e33994_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_type', '-timestamp'], name='audit_audit_resourc_965430_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address', '-timestamp'], name='audit_audit_ip_addr_ed092b_idx'),
        ),
    ]
