# Generated by Django 4.2.7 on 2025-11-24 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('audit', '0008_create_audit_log_professional'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='additional_info',
            field=models.TextField(blank=True, help_text="Informations complémentaires sur l'action", null=True, verbose_name='Informations supplémentaires'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='changes_after',
            field=models.JSONField(blank=True, help_text='État de la ressource après modification (format JSON)', null=True, verbose_name='Modifications après'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='changes_before',
            field=models.JSONField(blank=True, help_text='État de la ressource avant modification (format JSON)', null=True, verbose_name='Modifications avant'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Type de modèle concerné', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Type de contenu'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text="Identifiant de l'objet concerné", null=True, verbose_name="ID de l'objet"),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('FAILED_LOGIN', 'Échec de connexion'), ('VIEW', 'Consultation'), ('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('DOWNLOAD', 'Téléchargement'), ('SEARCH', 'Recherche'), ('SUSPEND', 'Suspension'), ('RESTORE', 'Restauration'), ('PERMISSION_CHANGE', 'Changement de permissions'), ('ACCESS_DENIED', 'Accès refusé')], db_index=True, max_length=50, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='data_after',
            field=models.JSONField(blank=True, default=dict, help_text='État de la ressource après modification (format JSON) - Déprécié, utiliser changes_after', null=True, verbose_name='Données après'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='data_before',
            field=models.JSONField(blank=True, default=dict, help_text='État de la ressource avant modification (format JSON) - Déprécié, utiliser changes_before', null=True, verbose_name='Données avant'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource_id',
            field=models.CharField(blank=True, db_index=True, help_text='Identifiant de la ressource concernée - Déprécié, utiliser object_id', max_length=100, null=True, verbose_name='ID de la ressource'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource_type',
            field=models.CharField(blank=True, db_index=True, help_text='Type de ressource concernée (ex: Utilisateur, DossierCriminel, Preuve) - Déprécié, utiliser content_type', max_length=255, null=True, verbose_name='Type de ressource'),
        ),
    ]
