# Generated by Django 4.2.7 on 2025-11-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0012_add_description_short_and_improve_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='changes_after',
            field=models.JSONField(blank=True, help_text='État de la ressource après modification (format JSON) - Déprécié, utiliser after', null=True, verbose_name='Modifications après'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='changes_before',
            field=models.JSONField(blank=True, help_text='État de la ressource avant modification (format JSON) - Déprécié, utiliser before', null=True, verbose_name='Modifications avant'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='data_after',
            field=models.JSONField(blank=True, default=dict, help_text='État de la ressource après modification (format JSON) - Déprécié, utiliser after', null=True, verbose_name='Données après'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='data_before',
            field=models.JSONField(blank=True, default=dict, help_text='État de la ressource avant modification (format JSON) - Déprécié, utiliser before', null=True, verbose_name='Données avant'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='description',
            field=models.TextField(blank=True, help_text="Description textuelle générée automatiquement pour l'interface (format long lisible)", null=True, verbose_name='Description'),
        ),
    ]
