# Generated by Django 4.2.7 on 2025-11-26 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0013_alter_auditlog_changes_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='description_after',
            field=models.TextField(blank=True, help_text="État ou description après l'action", null=True, verbose_name='Description après'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='description_before',
            field=models.TextField(blank=True, help_text="État ou description avant l'action", null=True, verbose_name='Description avant'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text="Heure de fin de l'action (généralement celle de la session)", null=True, verbose_name='Heure de fin'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='operation_index',
            field=models.IntegerField(blank=True, db_index=True, help_text="Numéro séquentiel de l'opération pour le jour", null=True, verbose_name="Index d'opération"),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='reference',
            field=models.CharField(blank=True, db_index=True, help_text='Référence professionnelle unique (ex: SGIC-AUD/2025/11/26/ADM-TOJO/000142)', max_length=255, null=True, unique=True, verbose_name='Référence audit'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text="Heure de début de l'action (généralement celle de la session)", null=True, verbose_name='Heure de début'),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Clé de session Django')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('start_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Heure de début')),
                ('end_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Heure de fin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Session Utilisateur',
                'verbose_name_plural': 'Sessions Utilisateur',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddField(
            model_name='auditlog',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Session utilisateur associée à cette action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='audit.usersession', verbose_name='Session'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['-start_time'], name='audit_users_start_t_b8fd01_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', '-start_time'], name='audit_users_user_id_d5d207_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key'], name='audit_users_session_6ab973_idx'),
        ),
    ]
