# Generated by Django 4.2.7 on 2026-01-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0014_add_user_session_and_professional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='frontend_route',
            field=models.CharField(blank=True, db_index=True, help_text="Route/écran visité dans l'application React (ex: /dashboard, /enquetes, /fiches-criminelles)", max_length=500, null=True, verbose_name='Route frontend'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='screen_name',
            field=models.CharField(blank=True, db_index=True, help_text="Nom descriptif de l'écran visité (ex: Dashboard, Liste des enquêtes, Détails fiche criminelle)", max_length=255, null=True, verbose_name="Nom de l'écran"),
        ),
    ]
