# Generated by Django 4.2.7 on 2026-01-05 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0017_add_frontend_route_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('FAILED_LOGIN', 'Échec de connexion'), ('VIEW', 'Consultation'), ('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('DOWNLOAD', 'Téléchargement'), ('UPLOAD', 'Téléversement'), ('SEARCH', 'Recherche'), ('SUSPEND', 'Suspension'), ('RESTORE', 'Restauration'), ('PERMISSION_CHANGE', 'Changement de permissions'), ('ROLE_CHANGE', 'Changement de rôle'), ('PIN_VALIDATION', 'Validation de PIN'), ('PIN_FAILED', 'Échec de validation PIN'), ('ACCESS_DENIED', 'Accès refusé'), ('NAVIGATION', 'Navigation'), ('ERROR_403', 'Erreur 403 - Accès refusé'), ('ERROR_404', 'Erreur 404 - Page non trouvée'), ('ERROR_500', 'Erreur 500 - Erreur serveur')], db_index=True, max_length=50, verbose_name='Action'),
        ),
        migrations.CreateModel(
            name='JournalAuditNarratif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date et heure de début de la session', verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, db_index=True, help_text='Date et heure de fin de la session', null=True, verbose_name='Date de fin')),
                ('description_narrative', models.TextField(blank=True, default='', help_text="Journal narratif complet et chronologique de toutes les actions de la session. Ce champ s'enrichit progressivement et ne peut pas être modifié après clôture.", verbose_name='Description narrative')),
                ('est_cloture', models.BooleanField(default=False, help_text='Indique si le journal est clôturé (session terminée)', verbose_name='Journal clôturé')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('browser', models.CharField(blank=True, max_length=255, null=True, verbose_name='Navigateur')),
                ('os', models.CharField(blank=True, max_length=255, null=True, verbose_name="Système d'exploitation")),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Dernière mise à jour')),
                ('session', models.OneToOneField(help_text='Session associée à ce journal narratif', on_delete=django.db.models.deletion.CASCADE, related_name='journal_narratif', to='audit.usersession', verbose_name='Session utilisateur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journaux_narratifs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'Audit Narratif",
                'verbose_name_plural': "Journaux d'Audit Narratifs",
                'ordering': ['-date_debut'],
                'indexes': [models.Index(fields=['-date_debut'], name='audit_journ_date_de_47b18f_idx'), models.Index(fields=['user', '-date_debut'], name='audit_journ_user_id_8c1263_idx'), models.Index(fields=['est_cloture', '-date_debut'], name='audit_journ_est_clo_69a19c_idx')],
            },
        ),
    ]
