# Generated by Django 4.2.7 on 2026-01-08 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0018_alter_auditlog_action_journalauditnarratif'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100, verbose_name='Rôle')),
                ('module', models.CharField(db_index=True, help_text='Module concerné (ex: Auth, Criminel, IA)', max_length=100, verbose_name='Module')),
                ('action', models.CharField(db_index=True, help_text='Action effectuée (ex: Téléchargement rapport)', max_length=255, verbose_name='Action')),
                ('ressource', models.CharField(help_text='Ressource concernée', max_length=255, verbose_name='Ressource')),
                ('narration', models.TextField(help_text="Description narrative détaillée de l'action", verbose_name='Narration')),
                ('ip', models.GenericIPAddressField(db_index=True, verbose_name='Adresse IP')),
                ('navigateur', models.CharField(max_length=255, verbose_name='Navigateur')),
                ('os', models.CharField(max_length=100, verbose_name="Système d'exploitation")),
                ('methode_http', models.CharField(max_length=10, verbose_name='Méthode HTTP')),
                ('date_action', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Date de l'action")),
                ('reference_audit', models.CharField(db_index=True, help_text='Référence unique SGIC-AUDIT-YYYYMMDD-HHMMSS', max_length=100, unique=True, verbose_name="Référence d'audit")),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'Audit",
                'verbose_name_plural': "Journaux d'Audit",
                'db_table': 'audit_journal_audit_narratif',
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['-date_action'], name='audit_journ_date_ac_42c80d_idx'), models.Index(fields=['module', '-date_action'], name='audit_journ_module_81ff2e_idx'), models.Index(fields=['utilisateur', '-date_action'], name='audit_journ_utilisa_75b56a_idx'), models.Index(fields=['reference_audit'], name='audit_journ_referen_0a60c8_idx')],
            },
        ),
    ]
