# Generated by Django 4.2.7 on 2026-01-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0019_create_journal_audit_narratif'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='narrative_text',
            field=models.CharField(blank=True, help_text='Texte narratif explicite de l\'action (format: "Le [date] à [heure], [utilisateur] a [action] depuis l\'IP [ip]")', max_length=1000, null=True, verbose_name='Texte narratif'),
        ),
    ]
