# Generated by Django 4.2.7 on 2025-12-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upr', '0002_alter_unidentifiedperson_id_alter_uprmatchlog_id'),
        ('upr', '0002_simplify_upr_model'),
    ]

    operations = [
    ]
