# Generated by Django 4.2.7 on 2025-12-06 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upr', '0003_merge_20251206_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidentifiedperson',
            options={'ordering': ['-date_enregistrement'], 'verbose_name': 'Personne Non Identifiée', 'verbose_name_plural': 'Personnes Non Identifiées'},
        ),
        migrations.AddField(
            model_name='unidentifiedperson',
            name='empreinte_digitale',
            field=models.ImageField(blank=True, help_text='Empreinte digitale (optionnelle) pour la reconnaissance dactyloscopique', null=True, upload_to='upr/empreintes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Empreinte digitale'),
        ),
        migrations.AlterField(
            model_name='unidentifiedperson',
            name='notes',
            field=models.TextField(blank=True, help_text='Observations et informations complémentaires', null=True, verbose_name='Notes'),
        ),
        migrations.DeleteModel(
            name='UPRMatchLog',
        ),
    ]
