# Generated by Django 4.2.7 on 2025-12-06 19:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('criminel', '0024_alter_criminalinfraction_statut_affaire_and_more'),
        ('upr', '0004_alter_unidentifiedperson_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriminelMatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(help_text='Distance L2 entre les embeddings (plus petit = plus similaire)', verbose_name='Distance L2')),
                ('match_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de correspondance')),
                ('is_strict_match', models.BooleanField(default=False, help_text='True si distance < 0.90 (correspondance très probable)', verbose_name='Correspondance stricte')),
                ('is_weak_match', models.BooleanField(default=False, help_text='True si distance < 1.20 (correspondance possible)', verbose_name='Correspondance faible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Correspondance UPR-Criminel',
                'verbose_name_plural': 'Correspondances UPR-Criminel',
                'db_table': 'sgic_criminelmatchlog',
                'ordering': ['-match_date', 'distance'],
            },
        ),
        migrations.CreateModel(
            name='UPRMatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(help_text='Distance L2 entre les embeddings (plus petit = plus similaire)', verbose_name='Distance L2')),
                ('match_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de correspondance')),
                ('is_strict_match', models.BooleanField(default=False, help_text='True si distance < 0.90 (correspondance très probable)', verbose_name='Correspondance stricte')),
                ('is_weak_match', models.BooleanField(default=False, help_text='True si distance < 1.20 (correspondance possible)', verbose_name='Correspondance faible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Correspondance UPR-UPR',
                'verbose_name_plural': 'Correspondances UPR-UPR',
                'db_table': 'sgic_uprmatchlog',
                'ordering': ['-match_date', 'distance'],
            },
        ),
        migrations.RemoveField(
            model_name='unidentifiedperson',
            name='photo_face',
        ),
        migrations.AddField(
            model_name='unidentifiedperson',
            name='context_location',
            field=models.CharField(blank=True, help_text="Lieu où l'individu a été découvert ou trouvé", max_length=255, null=True, verbose_name='Lieu de découverte'),
        ),
        migrations.AddField(
            model_name='unidentifiedperson',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant créé cet UPR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upr_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='unidentifiedperson',
            name='discovered_date',
            field=models.DateTimeField(blank=True, help_text="Date et heure de découverte de l'individu", null=True, verbose_name='Date de découverte'),
        ),
        migrations.AddField(
            model_name='unidentifiedperson',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text="Indique si l'UPR a été résolu (fusionné avec un criminel identifié)", verbose_name='Résolu'),
        ),
        migrations.AddField(
            model_name='unidentifiedperson',
            name='landmarks_106',
            field=models.JSONField(blank=True, help_text='Liste des 106 points de repère faciaux [[x, y], ...] extraits par InsightFace', null=True, verbose_name='Landmarks 106 points'),
        ),
        migrations.AddField(
            model_name='unidentifiedperson',
            name='profil_face',
            field=models.ImageField(default=1, help_text='Photo obligatoire du visage de face', upload_to='upr/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Photo de face'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidentifiedperson',
            name='profil_left',
            field=models.ImageField(blank=True, help_text='Photo de profil gauche (optionnelle)', null=True, upload_to='upr/photos/', verbose_name='Photo profil gauche'),
        ),
        migrations.AddField(
            model_name='unidentifiedperson',
            name='profil_right',
            field=models.ImageField(blank=True, help_text='Photo de profil droit (optionnelle)', null=True, upload_to='upr/photos/', verbose_name='Photo profil droit'),
        ),
        migrations.AddField(
            model_name='unidentifiedperson',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text="Date à laquelle l'UPR a été résolu", null=True, verbose_name='Date de résolution'),
        ),
        migrations.AddField(
            model_name='unidentifiedperson',
            name='resolved_to_criminel',
            field=models.ForeignKey(blank=True, help_text='Criminel identifié vers lequel cet UPR a été fusionné', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upr_resolved', to='criminel.criminalfichecriminelle', verbose_name='Résolu vers criminel'),
        ),
        migrations.AlterField(
            model_name='unidentifiedperson',
            name='face_embedding',
            field=models.JSONField(blank=True, help_text="Vecteur d'embedding ArcFace de 512 dimensions (format JSON array de floats)", null=True, verbose_name='Embedding ArcFace 512D'),
        ),
        migrations.AddIndex(
            model_name='unidentifiedperson',
            index=models.Index(fields=['code_upr'], name='sgic_uniden_code_up_104dee_idx'),
        ),
        migrations.AddIndex(
            model_name='unidentifiedperson',
            index=models.Index(fields=['-date_enregistrement'], name='sgic_uniden_date_en_debe8f_idx'),
        ),
        migrations.AddIndex(
            model_name='unidentifiedperson',
            index=models.Index(fields=['is_resolved'], name='sgic_uniden_is_reso_fadf14_idx'),
        ),
        migrations.AddIndex(
            model_name='unidentifiedperson',
            index=models.Index(fields=['created_by', '-date_enregistrement'], name='sgic_uniden_created_58a128_idx'),
        ),
        migrations.AlterModelTable(
            name='unidentifiedperson',
            table='sgic_unidentifiedperson',
        ),
        migrations.AddField(
            model_name='uprmatchlog',
            name='upr_source',
            field=models.ForeignKey(help_text='UPR pour lequel la correspondance a été trouvée', on_delete=django.db.models.deletion.CASCADE, related_name='matches_upr_source', to='upr.unidentifiedperson', verbose_name='UPR source'),
        ),
        migrations.AddField(
            model_name='uprmatchlog',
            name='upr_target',
            field=models.ForeignKey(help_text='UPR avec lequel la correspondance a été détectée', on_delete=django.db.models.deletion.CASCADE, related_name='matches_upr_target', to='upr.unidentifiedperson', verbose_name='UPR cible'),
        ),
        migrations.AddField(
            model_name='criminelmatchlog',
            name='criminel_target',
            field=models.ForeignKey(help_text='Fiche criminelle avec laquelle la correspondance a été détectée', on_delete=django.db.models.deletion.CASCADE, related_name='matches_upr', to='criminel.criminalfichecriminelle', verbose_name='Criminel cible'),
        ),
        migrations.AddField(
            model_name='criminelmatchlog',
            name='upr_source',
            field=models.ForeignKey(help_text='UPR pour lequel la correspondance a été trouvée', on_delete=django.db.models.deletion.CASCADE, related_name='matches_criminel', to='upr.unidentifiedperson', verbose_name='UPR source'),
        ),
        migrations.AddIndex(
            model_name='uprmatchlog',
            index=models.Index(fields=['upr_source', '-match_date'], name='sgic_uprmat_upr_sou_f5b22e_idx'),
        ),
        migrations.AddIndex(
            model_name='uprmatchlog',
            index=models.Index(fields=['upr_target', '-match_date'], name='sgic_uprmat_upr_tar_1af4fc_idx'),
        ),
        migrations.AddIndex(
            model_name='uprmatchlog',
            index=models.Index(fields=['distance'], name='sgic_uprmat_distanc_8f2213_idx'),
        ),
        migrations.AddIndex(
            model_name='uprmatchlog',
            index=models.Index(fields=['is_strict_match'], name='sgic_uprmat_is_stri_fda419_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='uprmatchlog',
            unique_together={('upr_source', 'upr_target')},
        ),
        migrations.AddIndex(
            model_name='criminelmatchlog',
            index=models.Index(fields=['upr_source', '-match_date'], name='sgic_crimin_upr_sou_5c71d1_idx'),
        ),
        migrations.AddIndex(
            model_name='criminelmatchlog',
            index=models.Index(fields=['criminel_target', '-match_date'], name='sgic_crimin_crimine_30c280_idx'),
        ),
        migrations.AddIndex(
            model_name='criminelmatchlog',
            index=models.Index(fields=['distance'], name='sgic_crimin_distanc_b393b6_idx'),
        ),
        migrations.AddIndex(
            model_name='criminelmatchlog',
            index=models.Index(fields=['is_strict_match'], name='sgic_crimin_is_stri_f73553_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='criminelmatchlog',
            unique_together={('upr_source', 'criminel_target')},
        ),
    ]
