# Generated by Django 4.2.7 on 2025-12-08 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upr', '0005_criminelmatchlog_uprmatchlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(help_text='Identifiant unique de la caméra (ex: usb_0, ip_1)', max_length=100, unique=True, verbose_name='ID Caméra')),
                ('name', models.CharField(help_text='Nom descriptif de la caméra', max_length=255, verbose_name='Nom')),
                ('source', models.CharField(help_text='Index USB (0, 1, 2...) ou URL IP/RTSP', max_length=500, verbose_name='Source')),
                ('camera_type', models.CharField(choices=[('usb', 'USB'), ('ip', 'IP/RTSP')], default='usb', help_text='Type de caméra (USB ou IP/RTSP)', max_length=10, verbose_name='Type')),
                ('active', models.BooleanField(default=False, help_text='Indique si la caméra est actuellement active', verbose_name='Active')),
                ('last_seen', models.DateTimeField(blank=True, help_text='Dernière fois que la caméra a été vue/activée', null=True, verbose_name='Dernière vue')),
                ('frame_count', models.BigIntegerField(default=0, help_text='Nombre total de frames traitées', verbose_name='Nombre de frames')),
                ('detection_count', models.BigIntegerField(default=0, help_text='Nombre total de détections effectuées', verbose_name='Nombre de détections')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Caméra',
                'verbose_name_plural': 'Caméras',
                'db_table': 'sgic_camera',
                'ordering': ['camera_id'],
            },
        ),
        migrations.CreateModel(
            name='UPRLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('detection', 'Détection'), ('match_certain', 'Correspondance certaine'), ('match_probable', 'Correspondance probable'), ('accepted', 'Correspondance acceptée'), ('rejected', 'Correspondance rejetée')], help_text="Type d'action enregistrée", max_length=20, verbose_name='Action')),
                ('details', models.JSONField(default=dict, help_text='Détails de la détection (matches, scores, frame info, etc.)', verbose_name='Détails')),
                ('criminal_id', models.IntegerField(blank=True, help_text='ID de la fiche criminelle si correspondance trouvée', null=True, verbose_name='ID Criminel')),
                ('upr_id', models.IntegerField(blank=True, help_text="ID de l'UPR si correspondance trouvée", null=True, verbose_name='ID UPR')),
                ('match_score', models.FloatField(blank=True, help_text='Score de similarité (0.0-1.0)', null=True, verbose_name='Score de correspondance')),
                ('frame_url', models.URLField(blank=True, help_text="URL signée vers l'image de détection (si stockée)", max_length=500, null=True, verbose_name='URL Frame')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(blank=True, help_text='Caméra ayant généré la détection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='upr.camera', verbose_name='Caméra')),
                ('user', models.ForeignKey(blank=True, help_text="Utilisateur ayant effectué l'action (null si auto-détection)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upr_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Log UPR',
                'verbose_name_plural': 'Logs UPR',
                'db_table': 'sgic_uprlog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['camera_id'], name='sgic_camera_camera__1c8f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['active', '-last_seen'], name='sgic_camera_active_159b94_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['camera_type'], name='sgic_camera_camera__69f1db_idx'),
        ),
        migrations.AddIndex(
            model_name='uprlog',
            index=models.Index(fields=['-created_at'], name='sgic_uprlog_created_1f3e4d_idx'),
        ),
        migrations.AddIndex(
            model_name='uprlog',
            index=models.Index(fields=['camera', '-created_at'], name='sgic_uprlog_camera__bc7046_idx'),
        ),
        migrations.AddIndex(
            model_name='uprlog',
            index=models.Index(fields=['user', '-created_at'], name='sgic_uprlog_user_id_97f8f1_idx'),
        ),
        migrations.AddIndex(
            model_name='uprlog',
            index=models.Index(fields=['action', '-created_at'], name='sgic_uprlog_action_96fd22_idx'),
        ),
        migrations.AddIndex(
            model_name='uprlog',
            index=models.Index(fields=['criminal_id'], name='sgic_uprlog_crimina_727251_idx'),
        ),
        migrations.AddIndex(
            model_name='uprlog',
            index=models.Index(fields=['upr_id'], name='sgic_uprlog_upr_id_737f61_idx'),
        ),
    ]
