# Generated by Django 4.2.7 on 2026-01-06 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('criminel', '0024_alter_criminalinfraction_statut_affaire_and_more'),
        ('upr', '0006_camera_uprlog_camera_sgic_camera_camera__1c8f4f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_index', models.IntegerField(help_text='Index de la caméra utilisée (0 = intégrée, 1 = USB externe)', verbose_name='Index caméra')),
                ('camera_type', models.CharField(choices=[('integree', 'Caméra intégrée'), ('usb', 'Caméra USB externe')], default='integree', help_text='Type de caméra utilisée pour la capture', max_length=20, verbose_name='Type de caméra')),
                ('image', models.ImageField(help_text='Image capturée depuis la caméra', upload_to='camera/captures/', verbose_name='Image capturée')),
                ('capture_metadata', models.JSONField(blank=True, default=dict, help_text='Métadonnées techniques de la capture (résolution, qualité, etc.)', verbose_name='Métadonnées')),
                ('notes', models.TextField(blank=True, help_text='Notes et observations sur la capture', null=True, verbose_name='Notes')),
                ('captured_at', models.DateTimeField(auto_now_add=True, help_text='Date et heure exacte de la capture', verbose_name='Date de capture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(blank=True, help_text='Caméra utilisée pour la capture (intégrée ou USB)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captures', to='upr.camera', verbose_name='Caméra')),
                ('criminel', models.ForeignKey(blank=True, help_text='Fiche criminelle associée à cette capture (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_captures', to='criminel.criminalfichecriminelle', verbose_name='Fiche criminelle')),
                ('suspect_upr', models.ForeignKey(blank=True, help_text='Personne non identifiée (UPR) associée à cette capture (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_captures', to='upr.unidentifiedperson', verbose_name='Suspect UPR')),
                ('user', models.ForeignKey(help_text='Enquêteur ayant effectué la capture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_captures', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Capture caméra',
                'verbose_name_plural': 'Captures caméra',
                'db_table': 'sgic_camera_capture',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['-captured_at'], name='sgic_camera_capture_1bc214_idx'), models.Index(fields=['user', '-captured_at'], name='sgic_camera_user_id_aa0a1d_idx'), models.Index(fields=['camera', '-captured_at'], name='sgic_camera_camera__dbefd5_idx'), models.Index(fields=['criminel', '-captured_at'], name='sgic_camera_crimine_71282a_idx'), models.Index(fields=['suspect_upr', '-captured_at'], name='sgic_camera_suspect_82dc5f_idx'), models.Index(fields=['camera_index', '-captured_at'], name='sgic_camera_camera__e0ce90_idx')],
            },
        ),
    ]
