# Generated by Django 4.2.7 on 2026-01-10 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upr', '0007_add_camera_capture'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidentifiedperson',
            name='face_encoding',
            field=models.JSONField(blank=True, help_text="Vecteur d'encoding face_recognition de 128 dimensions (format JSON array de floats) pour reconnaissance rapide", null=True, verbose_name='Encoding face_recognition 128D'),
        ),
        migrations.AlterField(
            model_name='cameracapture',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Enquêteur ayant effectué la capture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_captures', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
