# Generated by Django 4.2.7 on 2026-06-16 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upr', '0009_add_archive_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='unidentifiedperson',
            new_name='sgic_uniden_is_arch_7d7b7a_idx',
            old_name='sgic_uniden_is_arch_abc123_idx',
        ),
    ]
