# Generated by Django 5.2.7 on 2025-10-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurmodel',
            name='dateCreation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateurmodel',
            name='derniereConnexion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
