# Generated by Django 5.2.7 on 2025-10-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_utilisateurmodel_datecreation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurmodel',
            name='derniereConnexion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
