# Generated by Django 4.2.7 on 2025-10-25 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_alter_utilisateurmodel_derniereconnexion'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConnectionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_connections', models.IntegerField(default=0)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('last_failed_login', models.DateTimeField(blank=True, null=True)),
                ('average_session_duration', models.IntegerField(blank=True, help_text='En secondes', null=True)),
                ('longest_session_duration', models.IntegerField(blank=True, help_text='En secondes', null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_login_device', models.CharField(blank=True, max_length=50, null=True)),
                ('last_login_location', models.CharField(blank=True, max_length=200, null=True)),
                ('suspicious_login_count', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statistiques de Connexion',
                'verbose_name_plural': 'Statistiques de Connexions',
                'db_table': 'utilisateur_connection_stats',
            },
        ),
        migrations.CreateModel(
            name='UserConnectionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('user_role', models.CharField(blank=True, max_length=100, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_name', models.CharField(blank=True, max_length=200, null=True)),
                ('redirect_url', models.CharField(blank=True, max_length=500, null=True)),
                ('redirect_success', models.BooleanField(default=False)),
                ('session_duration', models.IntegerField(blank=True, help_text='Durée en secondes', null=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Connexion Utilisateur',
                'verbose_name_plural': 'Connexions Utilisateurs',
                'db_table': 'utilisateur_connection_log',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user', '-login_time'], name='utilisateur_user_id_160bbc_idx'), models.Index(fields=['is_active'], name='utilisateur_is_acti_f96215_idx'), models.Index(fields=['-login_time'], name='utilisateur_login_t_7232c0_idx')],
            },
        ),
    ]
