# Generated by Django 4.2.7 on 2025-10-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0004_userconnectionstats_userconnectionlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateurmodel',
            options={'ordering': ['-dateCreation'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='utilisateurmodel',
            name='role',
            field=models.CharField(blank=True, choices=[('Administrateur Système', 'Administrateur Système'), ('Enquêteur Principal', 'Enquêteur Principal'), ('Enquêteur', 'Enquêteur'), ('Enquêteur Junior', 'Enquêteur Junior'), ('Analyste', 'Analyste'), ('Opérateur de Saisie', 'Opérateur de Saisie'), ('Superviseur', 'Superviseur')], help_text="Rôle de l'utilisateur dans le système", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateurmodel',
            name='statut',
            field=models.CharField(blank=True, choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu')], default='actif', max_length=20, null=True),
        ),
    ]
