# Generated by Django 4.2.7 on 2025-10-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0005_add_role_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurmodel',
            name='role',
            field=models.CharField(blank=True, choices=[('Administrateur Système', 'Administrateur Système'), ('Observateur', 'Observateur'), ('Enquêteur Principal', 'Enquêteur Principal'), ('Analyste', 'Analyste')], help_text="Rôle de l'utilisateur dans le système", max_length=100, null=True),
        ),
    ]
