# Generated by Django 4.2.7 on 2025-10-30 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0006_update_role_choices_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconnectionstats',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserConnectionLog',
        ),
        migrations.DeleteModel(
            name='UserConnectionStats',
        ),
    ]
