# Generated by Django 4.2.7 on 2025-10-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0007_remove_userconnectionstats_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurmodel',
            name='mfa_enabled',
            field=models.BooleanField(default=False, help_text='Authentification à deux facteurs activée', verbose_name='MFA activé'),
        ),
    ]
