# Generated by Django 4.2.7 on 2025-11-12 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0009_alter_utilisateurmodel_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFASecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(help_text='Clé secrète pour générer les codes TOTP', max_length=64, verbose_name='Clé secrète TOTP')),
                ('backup_codes', models.JSONField(blank=True, default=list, help_text='Codes de secours à usage unique', verbose_name='Codes de secours')),
                ('is_active', models.BooleanField(default=False, help_text='Indique si le MFA TOTP est activé pour cet utilisateur', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Dernière utilisation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_secret', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Clé secrète MFA',
                'verbose_name_plural': 'Clés secrètes MFA',
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(help_text="Clé secrète pour générer/vérifier l'OTP", max_length=64, verbose_name='Clé secrète')),
                ('otp_code', models.CharField(blank=True, help_text='Code OTP généré (optionnel, pour historique)', max_length=10, null=True, verbose_name='Code OTP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('expires_at', models.DateTimeField(help_text="Date d'expiration du code OTP (5 minutes par défaut)", verbose_name="Date d'expiration")),
                ('is_verified', models.BooleanField(default=False, help_text='Indique si le code OTP a été vérifié avec succès', verbose_name='Vérifié')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Adresse IP de la requête de vérification', null=True, verbose_name='Adresse IP')),
                ('method', models.CharField(choices=[('email', 'Email'), ('totp', 'TOTP (Google Authenticator)'), ('sms', 'SMS')], default='email', help_text="Méthode utilisée pour envoyer/générer l'OTP", max_length=20, verbose_name='Méthode')),
                ('attempts', models.IntegerField(default=0, help_text='Nombre de tentatives de vérification', verbose_name='Tentatives')),
                ('max_attempts', models.IntegerField(default=5, help_text='Nombre maximum de tentatives autorisées', verbose_name='Tentatives maximales')),
                ('blocked_until', models.DateTimeField(blank=True, help_text="Date jusqu'à laquelle l'utilisateur est bloqué après échecs répétés", null=True, verbose_name="Bloqué jusqu'à")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Vérification OTP',
                'verbose_name_plural': 'Vérifications OTP',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='utilisateur_user_id_ba62a9_idx'), models.Index(fields=['is_verified', 'expires_at'], name='utilisateur_is_veri_032f22_idx')],
            },
        ),
    ]
