# Generated by Django 4.2.7 on 2025-11-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0011_remove_otpcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='user',
        ),
        migrations.AlterField(
            model_name='utilisateurmodel',
            name='role',
            field=models.CharField(blank=True, choices=[('superAdmin', 'Super Administrateur'), ('Administrateur Système', 'Administrateur Système'), ('Observateur', 'Observateur'), ('Enquêteur Principal', 'Enquêteur Principal'), ('Enquêteur', 'Enquêteur'), ('Enquêteur Junior', 'Enquêteur Junior'), ('Analyste', 'Analyste')], help_text="Rôle de l'utilisateur dans le système", max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='MFASecret',
        ),
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
