# Generated by Django 4.2.7 on 2025-11-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0012_remove_otpverification_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurmodel',
            name='role',
            field=models.CharField(blank=True, choices=[('Administrateur Système', 'Administrateur Système'), ('Observateur', 'Observateur'), ('Enquêteur Principal', 'Enquêteur Principal'), ('Enquêteur', 'Enquêteur'), ('Enquêteur Junior', 'Enquêteur Junior'), ('Analyste', 'Analyste')], help_text="Rôle de l'utilisateur dans le système", max_length=100, null=True),
        ),
    ]
