# Generated by Django 4.2.7 on 2025-11-13 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0013_remove_superadmin_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateurmodel',
            name='mfa_enabled',
        ),
    ]
