# Generated by Django 4.2.7 on 2025-11-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0015_update_role_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurmodel',
            name='suspension_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
