# Generated by Django 4.2.7 on 2025-11-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0016_utilisateurmodel_suspension_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurmodel',
            name='archived_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'archivage"),
        ),
        migrations.AddField(
            model_name='utilisateurmodel',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archivé'),
        ),
    ]
