# Generated by Django 4.2.7 on 2025-11-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0019_userprofile_pinauditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pinauditlog',
            new_name='utilisateur_timesta_af0fd2_idx',
            old_name='utilisateur_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='pinauditlog',
            new_name='utilisateur_user_id_3f4ac0_idx',
            old_name='utilisateur_user_id_idx',
        ),
        migrations.AlterField(
            model_name='utilisateurmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
