# Generated by Django 4.2.7 on 2025-12-06 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0021_create_role_and_permissionsgic'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='permissionsgic',
            new_name='utilisateur_code_141c8f_idx',
            old_name='utilisateur_code_idx',
        ),
        migrations.RenameIndex(
            model_name='permissionsgic',
            new_name='utilisateur_categor_3fac9f_idx',
            old_name='utilisateur_category_idx',
        ),
        migrations.RenameIndex(
            model_name='role',
            new_name='utilisateur_name_529497_idx',
            old_name='utilisateur_name_idx',
        ),
        migrations.RenameIndex(
            model_name='role',
            new_name='utilisateur_is_acti_ec211b_idx',
            old_name='utilisateur_is_active_idx',
        ),
    ]
