# Generated by Django 4.2.7 on 2025-12-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0022_rename_utilisateur_code_idx_utilisateur_code_141c8f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurmodel',
            name='photo_profil',
            field=models.ImageField(blank=True, help_text="Photo de profil de l'utilisateur", null=True, upload_to='photos_profil/', verbose_name='Photo de profil'),
        ),
    ]
