# Generated by Django 4.2.7 on 2025-11-15 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('in_progress', 'En cours'), ('closed', 'Clôturé')], default='open', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'criminal_case',
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['province'], name='criminal_ca_provinc_6a8c40_idx'), models.Index(fields=['date_created'], name='criminal_ca_date_cr_542b82_idx'), models.Index(fields=['status'], name='criminal_ca_status_d1ed10_idx')],
            },
        ),
    ]
